#pragma once
// Thin header that re-includes the RE/flex generated lexer class
// and adds the state-hack methods used by the parser.

#include "asn1.tab.hh"    // Bison token types

// Include RE/flex generated header
#include "Lexer.l.hh"     // generated by reflex from asn1.l -> defines class Lexer

// The methods below are implemented at the end of asn1.l (%%...%% section)
// so they appear in the generated .cpp automatically.
