#!/usr/bin/env python3
"""
Generate static built-in alphabet tables for BuiltinTypes.cpp.

Each restricted ASN.1 string type needs two tables:
  k_<type>_alpha[N]   — decode: alpha[idx] → char value (sorted)
  k_<type>_enc[256]   — encode: enc[char] → idx | 0xFFFF

Run this script when the alphabet definitions change, then paste the output
into the table section of BuiltinTypes.cpp (between the TABLE-BEGIN / TABLE-END
markers).

Usage: python3 gen_builtin_tables.py
"""

import textwrap

TYPES = {
    "num": {
        "comment": "NumericString (X.680 §41.2): space + '0'..'9' — 11 chars, sorted ASCII.",
        "chars": list(" 0123456789"),
    },
    "prt": {
        "comment": "PrintableString (X.680 Table 8): 74 chars, sorted ASCII.",
        "chars": list(" '()+,-./"
                      "0123456789"
                      ":=?"
                      "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
                      "abcdefghijklmnopqrstuvwxyz"),
    },
    "ia5": {
        "comment": "IA5String (X.680 §41.4): 0x00..0x7F — 128 chars, sorted ASCII.",
        "chars": [chr(c) for c in range(0x00, 0x80)],
    },
    "vis": {
        "comment": "VisibleString (X.680 §41.6): printable ASCII 0x20..0x7E — 95 chars, sorted ASCII.",
        "chars": [chr(c) for c in range(0x20, 0x7F)],
    },
}

def fmt_alpha(name, comment, chars):
    vals = ", ".join(str(ord(c)) for c in sorted(chars))
    n = len(chars)
    lines = [f"// {comment}"]
    lines.append(f"static const uint8_t k_{name}_alpha[{n}] = {{")
    # wrap at ~100 chars
    lines.append("    " + vals)
    lines.append("};")
    return "\n".join(lines)

def fmt_enc(name, chars):
    enc = [0xFFFF] * 256
    for i, c in enumerate(sorted(chars)):
        enc[ord(c)] = i
    vals = []
    for v in enc:
        vals.append("0xFFFFu" if v == 0xFFFF else str(v))
    # format as 16-per-line block
    lines = [f"static const uint16_t k_{name}_enc[256] = {{"]
    for row in range(0, 256, 16):
        chunk = ", ".join(vals[row:row+16])
        lines.append(f"    {chunk},")
    # remove trailing comma from last line
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    return "\n".join(lines)

print("// ---- TABLE-BEGIN (generated by gen_builtin_tables.py) ----")
for name, info in TYPES.items():
    chars = info["chars"]
    print()
    print(fmt_alpha(name, info["comment"], chars))
    print(fmt_enc(name, chars))
print()
print("// ---- TABLE-END ----")
