//! SEQUENCE encode/decode — X.680 §24, X.690 §8.9.
//!
//! Table-driven, mirroring `SequenceBerHandler`
//! (`runtime/src/BerCodec.cpp`) and `SequenceSpec`/`MemberDescriptor`
//! (`runtime/include/asn1cpp/TypeDescriptor.hpp`): `encode_sequence`/
//! `decode_sequence` are generic, driven entirely by a `SequenceSpec<T>`
//! table — no per-type codegen'd traversal logic, no `switch`/`if` chains.
//! Member access goes through `MemberDescriptor`'s accessor functions
//! (`value.rs`'s module docs explain why every member uses a function, not
//! an `offsetof`-equivalent, unlike the C++ side's required-member fast path).
//!
//! `Point` (in `tests` below) is both the worked example and this module's
//! own test subject — it's real, table-driven code (not a stand-in), same
//! role as `test_seq_simple.cpp` on the C++ side and generated by
//! `RustBackend` for real ASN.1 schemas. Test-only (`#[cfg(test)]`, not
//! part of this crate's public API) — a worked example doesn't need to be
//! a permanent public type just to be readable as one.

use crate::reader::{DecodeError, Reader};
use crate::tag::{universal, Tag};
use crate::value::Asn1Value;
use crate::writer::write_constructed;
use crate::xer::XerReader;

pub const SEQUENCE_TAG: Tag = Tag::universal(universal::SEQUENCE, true);

/// SET's own natural tag (X.680 §26, universal 17,
/// constructed) — a SET-typed `SequenceSpec<T>` must use this instead of
/// `SEQUENCE_TAG`. `encode_sequence`/`decode_sequence` don't otherwise
/// distinguish SET from SEQUENCE (same TLV shape, same member walk; X.690
/// §8.11/§8.12 SET encoding is canonically member-tag-ordered on the wire,
/// which this crate doesn't enforce — same simplifying scope note
/// `decode_sequence`'s own doc already makes for member ordering generally).
pub const SET_TAG: Tag = Tag::universal(universal::SET, true);

/// One row in a `SequenceSpec<T>` table — mirrors `MemberDescriptor`
/// (`TypeDescriptor.hpp`), minus everything not yet needed by this crate's
/// scope (EXPLICIT/IMPLICIT tagging beyond the member's own natural tag,
/// CHOICE alternative dispatch — real gaps, not silently dropped:
/// `Backend`/codegen simply doesn't emit members needing them yet).
pub struct MemberDescriptor<T: 'static> {
    pub name: &'static str,
    pub tag: Tag,
    pub optional: bool,
    pub access: MemberAccess<T>,
    /// `Some` for a DEFAULT-valued member (X.680 §25.1) whose default value
    /// this crate can represent — mirrors `MemberDescriptor::set_default`
    /// (`TypeDescriptor.hpp`)/`SequenceBerHandler::decode_body`'s own
    /// `if (mbr.set_default) mbr.set_default(dest);` (`BerCodec.cpp`):
    /// `decode_sequence_content` calls this when the member's tag is absent
    /// from the wire, filling the schema default instead of leaving the
    /// field however `T::default()` left it. `None` for every other
    /// member, DEFAULT-valued or not — same "optional discriminant" shape
    /// `access`'s own variants use. No encode-side suppression: BER (unlike
    /// DER) never requires omitting a DEFAULT-equal value, and the C++
    /// runtime's own `SequenceBerHandler::encode` doesn't attempt it either
    /// (`default_value_cmp`, `TypeDescriptor.hpp`, is PER-only) — so a
    /// decoded-then-re-encoded DEFAULT member may legitimately gain an
    /// explicit tag it didn't have on the original wire, matching C++'s own
    /// behavior exactly, not a Rust-specific gap.
    pub set_default: Option<fn(&mut T)>,
}

/// How a member's value is reached and (de)serialized.
///
/// `Scalar` is the most common shape: the member is one field whose own
/// concrete type already implements `Asn1Value` (`i64`, `bool`, `Vec<u8>`,
/// `String`, an `Option<V>`/newtype-string, `SeqOf<T>`/`SetOf<T>` for a
/// SEQUENCE OF/SET OF member — every kind `rust_member_ber_tag` currently
/// covers), reached via the same accessor-function pair the crate has
/// always used (`value.rs`'s module doc explains why a function, not an
/// `offsetof`-equivalent). A SEQUENCE OF/SET OF member's field type is
/// `SeqOf<T>`/`SetOf<T>` rather than a raw `Vec<ElementType>` precisely so
/// it has a real `Asn1Value` impl and folds into this ordinary
/// `Scalar`/`TaggedScalar`/`ExplicitScalar` dispatch, with no special-casing
/// needed anywhere here.
pub enum MemberAccess<T: 'static> {
    Scalar {
        get: fn(&T) -> &dyn Asn1Value,
        get_mut: fn(&mut T) -> &mut dyn Asn1Value,
    },
    /// IMPLICIT tag override (X.690 §8.14). A member
    /// declared with its own `[n]` tag (explicit-in-the-schema, or an
    /// AUTOMATIC TAGS-assigned one) has that tag *replace* its type's
    /// natural one on the wire. Same shape as `Scalar` (`get`/`get_mut`,
    /// no closures) — the walker (`encode_sequence_content`/
    /// `decode_sequence_content` below) calls `Asn1Value::
    /// ber_encode_tagged`/`ber_decode_into_tagged` with the member's own
    /// `tag` field instead of the plain `ber_encode`/`ber_decode_into`
    /// `Scalar` uses; one generic trait method (`value.rs`) covers every
    /// kind, so no per-kind `*_tagged` primitive selection is needed here
    /// (or in codegen) at all. XER is unaffected either way — XER element
    /// tags are always field-name-derived, never type-derived (`xer.rs`'s
    /// module doc), so `get`/`get_mut` alone are already correct for that leg.
    TaggedScalar {
        get: fn(&T) -> &dyn Asn1Value,
        get_mut: fn(&mut T) -> &mut dyn Asn1Value,
    },
    /// EXPLICIT tagging (X.690 §8.14.3) — wraps the member's natural
    /// encoding in an outer TLV, rather than substituting the tag like
    /// `TaggedScalar`. Needs its own closures, unlike `TaggedScalar`:
    /// `value::decode_explicit` *constructs* a fresh value
    /// (`T: Asn1Value + Default`, monomorphized on the member's concrete
    /// type), it can't decode in place through a `&mut dyn Asn1Value`
    /// trait object the way `ber_decode_into_tagged` does — a trait object
    /// has no way to hand back a concrete, constructible `Self`. `get`/
    /// `get_mut` are carried too, XER-only (same field-name-derived-tag
    /// reasoning as `TaggedScalar` — EXPLICIT is purely a BER concept).
    ExplicitScalar {
        ber_encode: fn(&T, &mut Vec<u8>),
        ber_decode_into: fn(&mut T, &mut Reader) -> Result<(), DecodeError>,
        get: fn(&T) -> &dyn Asn1Value,
        get_mut: fn(&mut T) -> &mut dyn Asn1Value,
    },
    /// A `[n] ANY` member — X.208 legacy type, not defined in the current
    /// standard (X.680/X.690 don't mention it; X.691's own note treats a
    /// legacy ANY as an open type). No discriminant of its own (unlike
    /// CHOICE or a real open type keyed by a companion field) — an ANY
    /// member is not "one of several known types", it's raw captured bytes
    /// with no schema-visible way to know what they are. Always
    /// EXPLICIT-tagged when tagged (see `value::encode_explicit_any`'s
    /// doc) — field type is `Vec<u8>`, same Rust type as OCTET STRING, but
    /// holding raw captured TLV bytes rather than OCTET STRING content, so
    /// it can't reuse `Vec<u8>`'s own `Asn1Value` impl (that would wrap
    /// the capture in an extra OCTET STRING TLV). Mirrors the C++ side's
    /// `AnyBerHandler`/`asn_DEF_Any` (`runtime/src/BerCodec.cpp`/
    /// `BuiltinTypes.cpp`), which represent ANY the same way: an
    /// EXPLICIT-tagged member (`is_explicit = true` in the generated
    /// `MemberDescriptor`) storing raw bytes (`TypeLifecycleOps(TypeTag<
    /// OctetString>{})`), not a typed value. BER-only: ANY has no defined
    /// XER form here, no `get`/`get_mut`.
    ExplicitAny {
        ber_encode: fn(&T, &mut Vec<u8>),
        ber_decode_into: fn(&mut T, &mut Reader) -> Result<(), DecodeError>,
    },
    /// A member whose type/tag/optionality combination genuinely has no
    /// `Asn1Value` coverage yet in this crate. Every generated SEQUENCE/SET
    /// always gets a real table and `Asn1Value` impl now — nothing gates
    /// emission on every member being individually wire-representable
    /// first — so a member that isn't (a builtin storage/tag combination
    /// not yet implemented, or a member whose presence can't be safely
    /// detected at all, e.g. OPTIONAL typed by an untagged CHOICE with no
    /// tag to peek for) gets this instead: a struct containing one simply
    /// can't be successfully encoded/decoded via the generated methods
    /// yet, but every *other* member is unaffected, and — the actual
    /// point — any type that merely *references* this one as a composite
    /// member gets real coverage of its own regardless, since `Asn1Value`
    /// is always implemented, just not always successfully callable. No
    /// presence-detection is attempted (there's nothing safe to peek for
    /// in the cases that reach here) — reaching this row during either
    /// encode or decode panics unconditionally.
    Unsupported {
        reason: &'static str,
    },
}

/// Shared SEQUENCE-OF wire logic — one outer `SEQUENCE_TAG` TLV wrapping
/// zero or more inner element TLVs (X.690 §8.9); `SeqOf<T>::ber_encode_content`/
/// `ber_decode_content` (this module) delegate here, and `SetOf<T>`'s own
/// impl reuses the same content logic under its own `SET_TAG` (mirrors
/// `write_char_string`/`read_char_string` in `strings.rs` — one generic
/// function, many thin per-type call sites).
pub fn encode_seq_of<V: Asn1Value>(out: &mut Vec<u8>, items: &[V]) {
    encode_seq_of_tagged(out, SEQUENCE_TAG, items);
}

pub fn decode_seq_of<V: Asn1Value + Default>(r: &mut Reader) -> Result<Vec<V>, DecodeError> {
    decode_seq_of_tagged(r, SEQUENCE_TAG)
}

/// IMPLICIT tag override for a SEQUENCE OF/SET OF member,
/// same reasoning as `boolean::write_boolean_tagged`/`read_boolean_tagged`
/// — a member declared with its own `[n]` tag replaces the
/// natural `SEQUENCE_TAG`/`SET_TAG` on the *outer* TLV only; element
/// encoding/decoding is unaffected (elements keep their own natural tags).
pub fn encode_seq_of_tagged<V: Asn1Value>(out: &mut Vec<u8>, tag: Tag, items: &[V]) {
    let mut content = Vec::new();
    encode_seq_of_content(&mut content, items);
    write_constructed(out, tag, &content);
}

pub fn decode_seq_of_tagged<V: Asn1Value + Default>(
    r: &mut Reader,
    tag: Tag,
) -> Result<Vec<V>, DecodeError> {
    let tlv = r.read_tlv()?;
    if tlv.tag != tag {
        return Err(DecodeError::new(format!("expected SEQUENCE OF tag, got {:?}", tlv.tag), r.pos()));
    }
    decode_seq_of_content(tlv.value)
}

/// Content octets only (X.690 §8.9/§8.12) — the concatenation of each
/// element's own complete encoding, no outer TLV — for a named top-level
/// SEQUENCE OF/SET OF type's own `Asn1Value::ber_encode_content` (a real
/// newtype, not a plain alias, so it can implement the trait itself
/// exactly like SEQUENCE/CHOICE do — codegen wraps `Vec<V>` in
/// `pub struct X(pub Vec<V>);` for any *named* SEQUENCE OF/SET OF, since a
/// plain `pub type X = Vec<V>;` alias can't carry its own impl distinct
/// from whatever other ASN.1 type might also resolve to `Vec<V>`).
pub fn encode_seq_of_content<V: Asn1Value>(content: &mut Vec<u8>, items: &[V]) {
    for item in items {
        item.ber_encode(content);
    }
}

pub fn decode_seq_of_content<V: Asn1Value + Default>(content: &[u8]) -> Result<Vec<V>, DecodeError> {
    let mut inner = Reader::new(content);
    let mut result = Vec::new();
    while !inner.at_end() {
        let mut item = V::default();
        item.ber_decode_into(&mut inner)?;
        result.push(item);
    }
    Ok(result)
}

/// XER SEQUENCE-OF content: X.693 §12 wraps each element in a tag, all
/// nested directly inside the member's own `<name>...</name>` (no extra
/// container) — mirrors `SeqOfXerHandler` (`runtime/src/XerCodec.cpp`).
/// Per-element tag shape is delegated to `Asn1Value::xer_encode_seqof_element`
/// (builtin/composite: `<elem_name>content</elem_name>`; ENUMERATED/CHOICE/
/// NULL: their own self-delimiting form, no wrapper) — no codegen decision
/// required here for that split; `name_override` only ever matters to the
/// wrapped-form default.
pub fn encode_seq_of_xer<V: Asn1Value>(out: &mut String, items: &[V], depth: usize) {
    encode_seq_of_xer_named(out, items, depth, None);
}

/// `name_override` is `Some` for a SEQUENCE OF/SET OF that declared an
/// X.693 §12 element identifier (e.g. `SEQUENCE OF id INTEGER`) — the
/// generated top-level SeqOf newtype's own `xer_encode` passes
/// `SeqOfSpec::elem_xer_name` through here (see `emit_seq_of_definition`,
/// RustBackend.cpp). ENUMERATED/CHOICE/NULL elements ignore it (X.693
/// always uses their own self-delimiting tag regardless — `Generator.cpp`
/// doesn't even set `elem_xer_name` for a NULL element in the first place).
///
/// `depth` is *this collection's own* depth (matching `Asn1Value::
/// xer_encode`'s own "argument = my position" convention). Every element
/// writes its own leading `\n` + indent at `depth + 1`
/// (`Asn1Value::xer_encode_seqof_element`'s own doc) — most kinds add
/// nothing after their own closing tag, relying on the *next* element's
/// leading `\n` (or, for the last element, this function's own trailing
/// bit below) as the separator. CHOICE is the one exception: its own
/// element (`xer_encode_seqof_element`'s CHOICE override) adds a trailing
/// `\n` of its own too, matching `ChoiceXerHandler`'s own unconditional
/// `... << "</" << alt.name << ">\n"` (`runtime/src/XerCodec.cpp`) — when
/// two CHOICE elements sit back to back, that produces a genuine blank
/// line between them (confirmed against a real schema:
/// `Messaging-Property ::= CHOICE` used as a `SET OF` element — not a
/// bug, `SeqOfXerHandler`'s own loop only special-cases *its own* leading
/// newline for a non-CHOICE element, `if (!edef.choice_spec) { ...
/// os << s.indent(1); }`, so two adjacent CHOICE elements each
/// unconditionally contribute their own leading *and* trailing newline
/// with nothing to deduplicate them).
///
/// This function's own trailing bit — `\n` + `indent(depth)`, iff at
/// least one element was written (an empty collection contributes
/// nothing at all, matching `SeqOfXerHandler`'s own `count == 0` case —
/// the caller's `<name></name>` results automatically with no special
/// case needed here, same reasoning `encode_sequence_xer_content`'s own
/// empty-content case gives) — only adds the `\n` when the last element
/// didn't already end with one (CHOICE's own case): otherwise the two
/// would combine into an unwanted blank line right before the closing
/// tag, which real ground-truth output never has.
pub fn encode_seq_of_xer_named<V: Asn1Value>(out: &mut String, items: &[V], depth: usize, name_override: Option<&str>) {
    let start = out.len();
    for item in items {
        item.xer_encode_seqof_element(out, depth, name_override);
    }
    if out.len() > start {
        if !out.ends_with('\n') {
            out.push('\n');
        }
        out.push_str(&crate::xer::indent(depth));
    }
}

pub fn decode_seq_of_xer<V: Asn1Value + Default>(r: &mut XerReader) -> Result<Vec<V>, DecodeError> {
    decode_seq_of_xer_named(r, None)
}

/// Decode counterpart of `encode_seq_of_xer_named`. Loop termination is
/// purely "next tag is a closing tag" (mirrors `SeqOfXerHandler::decode`'s
/// `ti.closing && ti.name == def.name` check — the outer `<name>...</name>`
/// is already consumed by the caller before/after this runs, same as
/// there), not a per-element name comparison: the element's own tag varies
/// per item for ENUMERATED (value name) and CHOICE (chosen alternative),
/// so a fixed-name peek would wrongly stop after the first element.
pub fn decode_seq_of_xer_named<V: Asn1Value + Default>(r: &mut XerReader, name_override: Option<&str>) -> Result<Vec<V>, DecodeError> {
    let mut result = Vec::new();
    loop {
        let peeked = r.peek_tag();
        if peeked.closing || peeked.name.is_empty() {
            break;
        }
        let mut item = V::default();
        item.xer_decode_into_seqof_element(r, name_override)?;
        result.push(item);
    }
    Ok(result)
}

/// Generic SEQUENCE OF wrapper (see `SetOf<T>` just below for the SET OF
/// sibling) — gives a *named* SEQUENCE OF CHOICE alternative
/// (`RustBackend::rust_seqof_alt_mtype`) or SEQUENCE/SET *member*
/// (`RustBackend::emit_sequence_declaration`, both `compiler/src/codegen/
/// RustBackend.cpp`) a concrete `Asn1Value` impl without per-occurrence
/// codegen. A bare `Vec<T>` can't get one generically: a blanket
/// `impl<V: Asn1Value> Asn1Value for Vec<V>` would coherence-conflict with
/// `Vec<u8>`'s own concrete OCTET STRING impl (E0119 — at most one
/// unconstrained blanket impl per trait per crate). `SeqOf<T>` sidesteps
/// that by being a distinct type nothing else implements, so one blanket
/// impl below covers every element type — no per-occurrence synthesized
/// wrapper struct needed the way a top-level named `X ::= SEQUENCE OF Y`
/// still gets from `emit_seq_of_definition` (that one keeps its own real
/// ASN.1 name for XER wrapping when referenced elsewhere; a `SeqOf<T>`
/// alternative/member is wrapped by its own alternative/field name
/// instead, same as any other scalar member — never needs a name of its
/// own, hence `xer_element_name` below being a generic placeholder).
///
/// `ber_natural_tag` genuinely matters here, unlike a bare CHOICE
/// alternative (which always dispatches through its own resolved tag via
/// `ber_encode_tagged`/`ber_decode_into_tagged`, never this method): a
/// required SEQUENCE/SET *member* with no tag override goes through the
/// ordinary `MemberAccess::Scalar` path, whose `ber_encode`/`ber_decode_into`
/// (the `Asn1Value` trait's own default methods) reach for
/// `self.ber_natural_tag()` directly — and an EXPLICIT-tagged member's
/// inner TLV (X.690 §8.14.3: EXPLICIT wraps the value's own natural
/// encoding unchanged) reaches it exactly the same way through
/// `value::encode_explicit`/`decode_explicit`. `SeqOf<T>`/`SetOf<T>` being
/// two distinct types with two different `ber_natural_tag()` values is
/// what makes both paths correct automatically, with no separate
/// SEQUENCE-vs-SET signal needed anywhere in the generic walker
/// (`sequence.rs`/`xer.rs`) — RustBackend only has to pick which of the
/// two type names to put in the struct field declaration.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SeqOf<T>(pub Vec<T>);

impl<T> std::ops::Deref for SeqOf<T> {
    type Target = Vec<T>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<T> std::ops::DerefMut for SeqOf<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl<T: Asn1Value + Default> Asn1Value for SeqOf<T> {
    fn ber_natural_tag(&self) -> Tag {
        SEQUENCE_TAG
    }

    fn xer_element_name(&self) -> &'static str {
        "SEQUENCE-OF"
    }

    fn ber_encode_content(&self, out: &mut Vec<u8>) {
        encode_seq_of_content(out, &self.0);
    }

    fn ber_decode_content(&mut self, content: &[u8]) -> Result<(), DecodeError> {
        self.0 = decode_seq_of_content(content)?;
        Ok(())
    }

    fn xer_encode(&self, out: &mut String, depth: usize) {
        encode_seq_of_xer(out, &self.0, depth);
    }

    fn xer_decode_into(&mut self, r: &mut XerReader) -> Result<(), DecodeError> {
        self.0 = decode_seq_of_xer(r)?;
        Ok(())
    }
}

/// SET OF analogue of `SeqOf<T>` — identical shape, only `ber_natural_tag`
/// differs (X.680 §26: SET's own universal tag 17, not SEQUENCE's 16 —
/// see `SeqOf<T>`'s own doc for why that distinction genuinely matters
/// here, unlike a bare CHOICE alternative). A separate type, not a
/// generic parameter on `SeqOf<T>` itself, because `ber_natural_tag`
/// can't vary per-instantiation of the same type — Rust has no
/// compile-time value parameter to key it on here.
#[derive(Debug, Clone, Default, PartialEq)]
pub struct SetOf<T>(pub Vec<T>);

impl<T> std::ops::Deref for SetOf<T> {
    type Target = Vec<T>;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl<T> std::ops::DerefMut for SetOf<T> {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

impl<T: Asn1Value + Default> Asn1Value for SetOf<T> {
    fn ber_natural_tag(&self) -> Tag {
        SET_TAG
    }

    fn xer_element_name(&self) -> &'static str {
        "SET-OF"
    }

    fn ber_encode_content(&self, out: &mut Vec<u8>) {
        encode_seq_of_content(out, &self.0);
    }

    fn ber_decode_content(&mut self, content: &[u8]) -> Result<(), DecodeError> {
        self.0 = decode_seq_of_content(content)?;
        Ok(())
    }

    fn xer_encode(&self, out: &mut String, depth: usize) {
        encode_seq_of_xer(out, &self.0, depth);
    }

    fn xer_decode_into(&mut self, r: &mut XerReader) -> Result<(), DecodeError> {
        self.0 = decode_seq_of_xer(r)?;
        Ok(())
    }
}

/// SEQUENCE/SET member table — mirrors `SequenceSpec` (`TypeDescriptor.hpp`).
///
/// `name` is the XER element tag for the whole SEQUENCE (mirrors
/// `TypeDescriptor::name`, used by `SequenceXerHandler` — X.693's outer
/// element is the *type* name, unlike each member's own tag which is
/// *field*-name-derived). BER doesn't need it (BER dispatch is by `tag`
/// alone), but one table drives both encodings (see `lib.rs`'s XER module
/// doc), so it lives here rather than in a second, XER-only struct.
///
/// **Deliberate layering divergence from both C++ codebases**: in
/// `runtime/include/asn1cpp/TypeDescriptor.hpp`
/// `name` lives on the outer `TypeDescriptor`, a sibling to
/// `sequence_spec`/`choice_spec`/`enum_spec` — never inside `SequenceSpec`
/// itself. Same split in asn1c (`asn_TYPE_descriptor_s::name` vs.
/// `asn_SEQUENCE_specifics_s`, which carries no name at all). That layer
/// exists in both C++ codebases because their dispatch is runtime
/// polymorphic — one `TypeDescriptor*`/`asn_TYPE_descriptor_t*` has to
/// carry `name` regardless of *which* construct (`SEQUENCE`/`CHOICE`/
/// `ENUMERATED`) it points at, since the codec picks the handler at
/// runtime via `TypeKind`/`tag2el`. Rust's design has no such layer:
/// dispatch is by generic parameter (`SequenceSpec<T>`) resolved at compile
/// time, so there is no shared runtime "type descriptor" object for `name`
/// to live on once, and introducing one here would only exist to satisfy
/// field-sharing, not to do anything. Each construct-specific spec (this
/// one, and `ChoiceSpec<T>` in `choice.rs`) carries its own
/// `name` — cheap (`&'static str`, one word, no allocation), and avoids
/// inventing indirection with no other purpose. Documented here so the
/// repetition in `ChoiceSpec<T>` reads as intentional, not a
/// copy-paste that forgot to deduplicate.
pub struct SequenceSpec<T: 'static> {
    pub name: &'static str,
    pub tag: Tag,
    pub members: &'static [MemberDescriptor<T>],
}

/// Member-loop content of a SEQUENCE encoding, without the outer TLV —
/// shared by `encode_sequence_tagged` (the top-level tag) and, once a
/// generated SEQUENCE/SET type has its own `Asn1Value` impl, by whatever
/// tag a *containing* type's member override applies (X.690 §8.14 IMPLICIT
/// retagging replaces the outer tag only, content is unchanged).
pub fn encode_sequence_content<T>(spec: &SequenceSpec<T>, value: &T, content: &mut Vec<u8>) {
    for m in spec.members {
        match &m.access {
            MemberAccess::Scalar { get, .. } => get(value).ber_encode(content),
            MemberAccess::TaggedScalar { get, .. } => get(value).ber_encode_tagged(m.tag, content),
            MemberAccess::ExplicitScalar { ber_encode, .. } => ber_encode(value, content),
            MemberAccess::ExplicitAny { ber_encode, .. } => ber_encode(value, content),
            MemberAccess::Unsupported { reason } => panic!("member '{}' not supported: {}", m.name, reason),
        }
    }
}

/// SEQUENCE encoding under an explicit tag override — the runtime
/// counterpart of a composite (SEQUENCE/SET-typed) member declared with its
/// own IMPLICIT `[n]` tag (X.690 §8.14.2): same content as `encode_sequence`,
/// different outer tag. Generic over any `SequenceSpec<T>`, so codegen needs
/// no per-type wiring beyond passing the member's resolved tag.
pub fn encode_sequence_tagged<T>(spec: &SequenceSpec<T>, value: &T, tag: Tag) -> Vec<u8> {
    let mut content = Vec::new();
    encode_sequence_content(spec, value, &mut content);
    let mut out = Vec::new();
    write_constructed(&mut out, tag, &content);
    out
}

/// Appends a SEQUENCE's complete TLV (its own natural tag) to an existing
/// buffer — the shape `Asn1Value::ber_encode` needs (writes into a
/// caller-owned `out`, not a fresh `Vec`) so a generated SEQUENCE/SET type
/// can implement that trait and become usable as a nested composite member.
pub fn encode_sequence_into<T>(spec: &SequenceSpec<T>, value: &T, out: &mut Vec<u8>) {
    out.extend_from_slice(&encode_sequence_tagged(spec, value, spec.tag));
}

/// Generic SEQUENCE encoder — the Rust analogue of
/// `SequenceBerHandler::encode`. Iterates `spec.members` in order, writing
/// each member's own complete TLV into the constructed SEQUENCE content.
/// OPTIONAL suppression needs no special-casing here: an
/// absent `Option<V>::None` member's `ber_encode` (the blanket
/// `Asn1Value for Option<V>` impl, `value.rs`) already writes nothing. No
/// DEFAULT-value suppression yet — a real gap, not silently dropped.
pub fn encode_sequence<T>(spec: &SequenceSpec<T>, value: &T) -> Vec<u8> {
    encode_sequence_tagged(spec, value, spec.tag)
}

/// Generic SEQUENCE decoder — the Rust analogue of
/// `SequenceBerHandler::decode`/`decode_body`. `T::default()` provides the
/// initial value (matching every generated struct's `#[derive(Default)]`);
/// each member is decoded in table order directly into its field via
/// `ber_decode_into`, no intermediate allocation per member.
///
/// OPTIONAL members: tag-presence detection, same model
/// `asn1cpp/CLAUDE.md`'s BER-vs-PER table documents ("OPTIONAL detection:
/// Tag present/absent in stream"). Peek before deciding whether to call
/// `ber_decode_into` at all — an absent optional member's tag belongs to
/// whatever comes *next* (the following member, or nothing), so the reader
/// must not be advanced past it if this member isn't present. Only a linear
/// scan (each optional member checked once, in table order) — correct for
/// SEQUENCE's canonical member ordering (X.690 §8.9), same simplifying
/// assumption `MemberDescriptor`'s module doc already documents this crate
/// making elsewhere (no out-of-order OPTIONAL members). An absent
/// DEFAULT-valued member (`m.set_default` — see `MemberDescriptor`'s own
/// doc) gets its schema default filled in here instead of being left
/// however `T::default()` left it.
pub fn decode_sequence_content<T: Default>(spec: &SequenceSpec<T>, inner: &mut Reader) -> Result<T, DecodeError> {
    let mut result = T::default();
    for m in spec.members {
        match &m.access {
            MemberAccess::Scalar { get_mut, .. } => {
                if m.optional {
                    if inner.peek_tag() == Some(m.tag) {
                        get_mut(&mut result).ber_decode_into(inner)?;
                    } else if let Some(set_default) = m.set_default {
                        set_default(&mut result);
                    }
                } else {
                    get_mut(&mut result).ber_decode_into(inner)?;
                }
            }
            MemberAccess::TaggedScalar { get_mut, .. } => {
                if m.optional {
                    if inner.peek_tag() == Some(m.tag) {
                        get_mut(&mut result).ber_decode_into_tagged(inner, m.tag)?;
                    } else if let Some(set_default) = m.set_default {
                        set_default(&mut result);
                    }
                } else {
                    get_mut(&mut result).ber_decode_into_tagged(inner, m.tag)?;
                }
            }
            MemberAccess::ExplicitScalar { ber_decode_into, .. } => {
                if m.optional {
                    if inner.peek_tag() == Some(m.tag) {
                        ber_decode_into(&mut result, inner)?;
                    } else if let Some(set_default) = m.set_default {
                        set_default(&mut result);
                    }
                } else {
                    ber_decode_into(&mut result, inner)?;
                }
            }
            MemberAccess::ExplicitAny { ber_decode_into, .. } => {
                if m.optional {
                    if inner.peek_tag() == Some(m.tag) {
                        ber_decode_into(&mut result, inner)?;
                    }
                } else {
                    ber_decode_into(&mut result, inner)?;
                }
            }
            MemberAccess::Unsupported { reason } => panic!("member '{}' not supported: {}", m.name, reason),
        }
    }
    Ok(result)
}

/// SEQUENCE decoding under an explicit tag override — the decode
/// counterpart of `encode_sequence_tagged`.
pub fn decode_sequence_tagged<T: Default>(spec: &SequenceSpec<T>, r: &mut Reader, tag: Tag) -> Result<T, DecodeError> {
    let tlv = r.read_tlv()?;
    if tlv.tag != tag {
        return Err(DecodeError::new(format!("expected SEQUENCE tag, got {:?}", tlv.tag), r.pos()));
    }
    let mut inner = Reader::new(tlv.value);
    decode_sequence_content(spec, &mut inner)
}

/// Reads a SEQUENCE (its own natural tag) from the caller's current stream
/// position — the shape `Asn1Value::ber_decode_into` needs (reads the next
/// TLV from a shared `Reader`, not a standalone buffer) so a generated
/// SEQUENCE/SET type can implement that trait and become usable as a nested
/// composite member.
pub fn decode_sequence_from<T: Default>(spec: &SequenceSpec<T>, r: &mut Reader) -> Result<T, DecodeError> {
    decode_sequence_tagged(spec, r, spec.tag)
}

pub fn decode_sequence<T: Default>(spec: &SequenceSpec<T>, data: &[u8]) -> Result<T, DecodeError> {
    let mut r = Reader::new(data);
    decode_sequence_from(spec, &mut r)
}


#[cfg(test)]
mod tests {
    use super::*;

/// `Point ::= SEQUENCE { x INTEGER, y INTEGER }`
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Point {
    pub x: i64,
    pub y: i64,
}

static POINT_MEMBERS: [MemberDescriptor<Point>; 2] = [
    MemberDescriptor {
        name: "x",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        access: MemberAccess::Scalar { get: |v| &v.x, get_mut: |v| &mut v.x },
        set_default: None,
    },
    MemberDescriptor {
        name: "y",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        access: MemberAccess::Scalar { get: |v| &v.y, get_mut: |v| &mut v.y },
        set_default: None,
    },
];

static POINT_SPEC: SequenceSpec<Point> =
    SequenceSpec { name: "Point", tag: SEQUENCE_TAG, members: &POINT_MEMBERS };

impl Point {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&POINT_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<Point, DecodeError> {
        decode_sequence(&POINT_SPEC, data)
    }

    pub fn encode_xer(&self) -> String {
        crate::xer::encode_sequence_xer(&POINT_SPEC, self)
    }

    pub fn decode_xer(xml: &str) -> Result<Point, DecodeError> {
        crate::xer::decode_sequence_xer(&POINT_SPEC, xml)
    }
}

/// `OptPoint ::= SEQUENCE { x INTEGER, y INTEGER OPTIONAL }` — worked
/// example + test subject for OPTIONAL member support,
/// same role `Point` plays for required-only members.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct OptPoint {
    pub x: i64,
    pub y: Option<i64>,
}

static OPT_POINT_MEMBERS: [MemberDescriptor<OptPoint>; 2] = [
    MemberDescriptor {
        name: "x",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        access: MemberAccess::Scalar { get: |v| &v.x, get_mut: |v| &mut v.x },
        set_default: None,
    },
    MemberDescriptor {
        name: "y",
        tag: crate::integer::INTEGER_TAG,
        optional: true,
        access: MemberAccess::Scalar { get: |v| &v.y, get_mut: |v| &mut v.y },
        set_default: None,
    },
];

static OPT_POINT_SPEC: SequenceSpec<OptPoint> =
    SequenceSpec { name: "OptPoint", tag: SEQUENCE_TAG, members: &OPT_POINT_MEMBERS };

impl OptPoint {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&OPT_POINT_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<OptPoint, DecodeError> {
        decode_sequence(&OPT_POINT_SPEC, data)
    }

    pub fn encode_xer(&self) -> String {
        crate::xer::encode_sequence_xer(&OPT_POINT_SPEC, self)
    }

    pub fn decode_xer(xml: &str) -> Result<OptPoint, DecodeError> {
        crate::xer::decode_sequence_xer(&OPT_POINT_SPEC, xml)
    }
}

/// `Coords ::= SEQUENCE { values SEQUENCE OF INTEGER }` — worked example +
/// test subject for a SEQUENCE OF member, same role `Point`/`OptPoint`
/// play for their own features. `values` is `SeqOf<i64>`, not a raw
/// `Vec<i64>` — a real `Asn1Value` impl, so this goes through the ordinary
/// `MemberAccess::Scalar` path exactly like any other composite member, no
/// dedicated SeqOf-shaped closures needed.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct Coords {
    pub values: SeqOf<i64>,
}

static COORDS_MEMBERS: [MemberDescriptor<Coords>; 1] = [MemberDescriptor {
    name: "values",
    tag: SEQUENCE_TAG,
    optional: false,
    access: MemberAccess::Scalar { get: |v| &v.values, get_mut: |v| &mut v.values },
    set_default: None,
}];

static COORDS_SPEC: SequenceSpec<Coords> =
    SequenceSpec { name: "Coords", tag: SEQUENCE_TAG, members: &COORDS_MEMBERS };

impl Coords {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&COORDS_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<Coords, DecodeError> {
        decode_sequence(&COORDS_SPEC, data)
    }

    pub fn encode_xer(&self) -> String {
        crate::xer::encode_sequence_xer(&COORDS_SPEC, self)
    }

    pub fn decode_xer(xml: &str) -> Result<Coords, DecodeError> {
        crate::xer::decode_sequence_xer(&COORDS_SPEC, xml)
    }
}

/// `OptCoords ::= SEQUENCE { values SEQUENCE OF INTEGER OPTIONAL }` — worked
/// example + test subject for OPTIONAL SEQUENCE OF member support, same
/// role `OptPoint` plays for OPTIONAL scalars. `Option<SeqOf<i64>>` gets
/// presence detection for free from the existing blanket
/// `impl<V: Asn1Value + Default> Asn1Value for Option<V>` (`value.rs`) —
/// no dedicated `is_present` closure needed.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct OptCoords {
    pub values: Option<SeqOf<i64>>,
}

static OPT_COORDS_MEMBERS: [MemberDescriptor<OptCoords>; 1] = [MemberDescriptor {
    name: "values",
    tag: SEQUENCE_TAG,
    optional: true,
    access: MemberAccess::Scalar { get: |v| &v.values, get_mut: |v| &mut v.values },
    set_default: None,
}];

static OPT_COORDS_SPEC: SequenceSpec<OptCoords> =
    SequenceSpec { name: "OptCoords", tag: SEQUENCE_TAG, members: &OPT_COORDS_MEMBERS };

impl OptCoords {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&OPT_COORDS_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<OptCoords, DecodeError> {
        decode_sequence(&OPT_COORDS_SPEC, data)
    }

    pub fn encode_xer(&self) -> String {
        crate::xer::encode_sequence_xer(&OPT_COORDS_SPEC, self)
    }

    pub fn decode_xer(xml: &str) -> Result<OptCoords, DecodeError> {
        crate::xer::decode_sequence_xer(&OPT_COORDS_SPEC, xml)
    }
}

/// `SetCoords ::= SEQUENCE { values SET OF INTEGER }` — worked example +
/// test subject for a SET OF *member*, distinct from `Coords`'s SEQUENCE
/// OF: `values` is `SetOf<i64>`, whose own `ber_natural_tag()` is SET_TAG
/// (universal 17), not SEQUENCE_TAG (universal 16) — `APointSet` below
/// already covers a top-level SET's own tag; this is the member-level
/// case. Same `MemberAccess::Scalar` path as `Coords`, just a different
/// field type.
#[derive(Debug, Clone, PartialEq, Default)]
pub struct SetCoords {
    pub values: SetOf<i64>,
}

static SET_COORDS_MEMBERS: [MemberDescriptor<SetCoords>; 1] = [MemberDescriptor {
    name: "values",
    tag: SET_TAG,
    optional: false,
    access: MemberAccess::Scalar { get: |v| &v.values, get_mut: |v| &mut v.values },
    set_default: None,
}];

static SET_COORDS_SPEC: SequenceSpec<SetCoords> =
    SequenceSpec { name: "SetCoords", tag: SEQUENCE_TAG, members: &SET_COORDS_MEMBERS };

impl SetCoords {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&SET_COORDS_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<SetCoords, DecodeError> {
        decode_sequence(&SET_COORDS_SPEC, data)
    }
}

/// `DefaultPoint ::= SEQUENCE { x INTEGER, y INTEGER DEFAULT 42 }` — worked
/// example + test subject for a DEFAULT-valued member (X.680 §25.1): `y`'s
/// `MemberDescriptor::set_default` fills in `42` when absent from the wire,
/// same role `OptPoint`'s `y` plays for plain OPTIONAL (no default value).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct DefaultPoint {
    pub x: i64,
    pub y: Option<i64>,
}

fn default_point_y_default() -> i64 {
    42
}

static DEFAULT_POINT_MEMBERS: [MemberDescriptor<DefaultPoint>; 2] = [
    MemberDescriptor {
        name: "x",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        access: MemberAccess::Scalar { get: |v| &v.x, get_mut: |v| &mut v.x },
        set_default: None,
    },
    MemberDescriptor {
        name: "y",
        tag: crate::integer::INTEGER_TAG,
        optional: true,
        access: MemberAccess::Scalar { get: |v| &v.y, get_mut: |v| &mut v.y },
        set_default: Some(|v| v.y = Some(default_point_y_default())),
    },
];

static DEFAULT_POINT_SPEC: SequenceSpec<DefaultPoint> =
    SequenceSpec { name: "DefaultPoint", tag: SEQUENCE_TAG, members: &DEFAULT_POINT_MEMBERS };

impl DefaultPoint {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&DEFAULT_POINT_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<DefaultPoint, DecodeError> {
        decode_sequence(&DEFAULT_POINT_SPEC, data)
    }
}


    #[test]
    fn encodes_hand_computed_vector() {
        let p = Point { x: 1, y: 2 };
        // SEQUENCE (0x30), length 6, then two INTEGER TLVs (0x02 0x01 0x01, 0x02 0x01 0x02).
        assert_eq!(
            p.encode(),
            vec![0x30, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]
        );
    }

    #[test]
    fn round_trips() {
        let p = Point { x: -5, y: 300 };
        let bytes = p.encode();
        assert_eq!(Point::decode(&bytes).unwrap(), p);
    }

    #[test]
    fn wrong_tag_is_error() {
        let data = [0x02, 0x01, 0x05]; // INTEGER tag, not SEQUENCE
        assert!(Point::decode(&data).is_err());
    }

    #[test]
    fn truncated_second_field_is_error() {
        // SEQUENCE containing only one INTEGER, second read must fail.
        let data = [0x30, 0x03, 0x02, 0x01, 0x01];
        assert!(Point::decode(&data).is_err());
    }

    #[test]
    fn xer_encodes_hand_computed_vector() {
        // Matches SequenceXerHandler's output shape (runtime/src/XerCodec.cpp):
        // <Point>\n    <x>3</x>\n    <y>4</y>\n</Point>\n
        let p = Point { x: 3, y: 4 };
        assert_eq!(p.encode_xer(), "<Point>\n    <x>3</x>\n    <y>4</y>\n</Point>\n");
    }

    #[test]
    fn xer_round_trips() {
        let p = Point { x: -5, y: 300 };
        let xml = p.encode_xer();
        assert_eq!(Point::decode_xer(&xml).unwrap(), p);
    }

    #[test]
    fn xer_zero_round_trips() {
        let p = Point { x: 0, y: 0 };
        let xml = p.encode_xer();
        assert_eq!(xml, "<Point>\n    <x>0</x>\n    <y>0</y>\n</Point>\n");
        assert_eq!(Point::decode_xer(&xml).unwrap(), p);
    }

    #[test]
    fn xer_wrong_outer_tag_is_error() {
        assert!(Point::decode_xer("<NotPoint><x>1</x><y>2</y></NotPoint>").is_err());
    }

    #[test]
    fn xer_truncated_is_error() {
        assert!(Point::decode_xer("<Point>\n    <x>3</x>\n</Point>\n").is_err());
    }

    // ---- OPTIONAL member support -------------------------

    #[test]
    fn opt_present_ber_round_trips() {
        let p = OptPoint { x: 1, y: Some(2) };
        let bytes = p.encode();
        assert_eq!(bytes, vec![0x30, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]);
        assert_eq!(OptPoint::decode(&bytes).unwrap(), p);
    }

    #[test]
    fn opt_absent_ber_round_trips() {
        let p = OptPoint { x: 1, y: None };
        let bytes = p.encode();
        // Only the required member's TLV — no trace of y at all.
        assert_eq!(bytes, vec![0x30, 0x03, 0x02, 0x01, 0x01]);
        assert_eq!(OptPoint::decode(&bytes).unwrap(), p);
    }

    #[test]
    fn opt_present_xer_round_trips() {
        let p = OptPoint { x: 1, y: Some(2) };
        let xml = p.encode_xer();
        assert_eq!(xml, "<OptPoint>\n    <x>1</x>\n    <y>2</y>\n</OptPoint>\n");
        assert_eq!(OptPoint::decode_xer(&xml).unwrap(), p);
    }

    #[test]
    fn opt_absent_xer_round_trips() {
        let p = OptPoint { x: 1, y: None };
        let xml = p.encode_xer();
        // No <y> element at all when absent.
        assert_eq!(xml, "<OptPoint>\n    <x>1</x>\n</OptPoint>\n");
        assert_eq!(OptPoint::decode_xer(&xml).unwrap(), p);
    }

    // ---- SET vs SEQUENCE outer tag ------------------------

    #[test]
    fn set_tag_is_seventeen_constructed() {
        assert_eq!(SET_TAG, Tag::universal(17, true));
        assert_ne!(SET_TAG, SEQUENCE_TAG);
    }

    #[test]
    fn set_uses_its_own_tag_not_sequences() {
        static SET_MEMBERS: [MemberDescriptor<Point>; 2] = [
            MemberDescriptor {
                name: "x",
                tag: crate::integer::INTEGER_TAG,
                optional: false,
                access: MemberAccess::Scalar { get: |v| &v.x, get_mut: |v| &mut v.x },
                set_default: None,
            },
            MemberDescriptor {
                name: "y",
                tag: crate::integer::INTEGER_TAG,
                optional: false,
                access: MemberAccess::Scalar { get: |v| &v.y, get_mut: |v| &mut v.y },
                set_default: None,
            },
        ];
        static A_SET_SPEC: SequenceSpec<Point> =
            SequenceSpec { name: "APointSet", tag: SET_TAG, members: &SET_MEMBERS };

        let p = Point { x: 1, y: 2 };
        let bytes = encode_sequence(&A_SET_SPEC, &p);
        // 0x31 = constructed (0x20) | SET's own tag number (17 = 0x11),
        // not 0x30 (SEQUENCE, universal 16).
        assert_eq!(bytes[0], 0x31);
        assert_eq!(decode_sequence(&A_SET_SPEC, &bytes).unwrap(), p);

        // A SEQUENCE-tagged decode of the same bytes must reject them —
        // proof the two tags are actually being distinguished, not just
        // cosmetically different constants.
        assert!(Point::decode(&bytes).is_err());
    }

    // ---- SEQUENCE OF members ------------------------------

    #[test]
    fn seq_of_ber_round_trips() {
        let c = Coords { values: SeqOf(vec![1, 2, 3]) };
        let bytes = c.encode();
        // Outer SEQUENCE (0x30) wraps the member's own SEQUENCE (0x30) of
        // three INTEGER TLVs.
        assert_eq!(
            bytes,
            vec![
                0x30, 0x0B, // outer SEQUENCE, len 11
                0x30, 0x09, // inner SEQUENCE OF, len 9
                0x02, 0x01, 0x01, 0x02, 0x01, 0x02, 0x02, 0x01, 0x03,
            ]
        );
        assert_eq!(Coords::decode(&bytes).unwrap(), c);
    }

    #[test]
    fn seq_of_empty_ber_round_trips() {
        let c = Coords { values: SeqOf(vec![]) };
        let bytes = c.encode();
        assert_eq!(bytes, vec![0x30, 0x02, 0x30, 0x00]);
        assert_eq!(Coords::decode(&bytes).unwrap(), c);
    }

    #[test]
    fn seq_of_xer_round_trips() {
        let c = Coords { values: SeqOf(vec![1, 2, 3]) };
        let xml = c.encode_xer();
        assert_eq!(
            xml,
            "<Coords>\n    <values>\n        <INTEGER>1</INTEGER>\n        <INTEGER>2</INTEGER>\n        <INTEGER>3</INTEGER>\n    </values>\n</Coords>\n"
        );
        assert_eq!(Coords::decode_xer(&xml).unwrap(), c);
    }

    #[test]
    fn seq_of_empty_xer_round_trips() {
        let c = Coords { values: SeqOf(vec![]) };
        let xml = c.encode_xer();
        assert_eq!(xml, "<Coords>\n    <values></values>\n</Coords>\n");
        assert_eq!(Coords::decode_xer(&xml).unwrap(), c);
    }

    // ---- OPTIONAL SEQUENCE OF member (gambas-asn1#400) -------

    #[test]
    fn optional_seq_of_present_ber_round_trips() {
        let c = OptCoords { values: Some(SeqOf(vec![1, 2])) };
        let bytes = c.encode();
        assert_eq!(
            bytes,
            vec![0x30, 0x08, 0x30, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]
        );
        assert_eq!(OptCoords::decode(&bytes).unwrap(), c);
    }

    #[test]
    fn optional_seq_of_absent_ber_round_trips_as_no_bytes() {
        let c = OptCoords { values: None };
        let bytes = c.encode();
        // Absent OPTIONAL SEQUENCE OF writes nothing at all — distinct from
        // present-but-empty (seq_of_empty_ber_round_trips), which still
        // writes an empty inner SEQUENCE OF TLV.
        assert_eq!(bytes, vec![0x30, 0x00]);
        assert_eq!(OptCoords::decode(&bytes).unwrap(), c);
    }

    #[test]
    fn optional_seq_of_present_but_empty_is_distinct_from_absent() {
        let present_empty = OptCoords { values: Some(SeqOf(vec![])) };
        let absent = OptCoords { values: None };
        assert_ne!(present_empty.encode(), absent.encode());
        assert_eq!(present_empty.encode(), vec![0x30, 0x02, 0x30, 0x00]);
    }

    #[test]
    fn optional_seq_of_present_xer_round_trips() {
        let c = OptCoords { values: Some(SeqOf(vec![1, 2])) };
        let xml = c.encode_xer();
        assert_eq!(
            xml,
            "<OptCoords>\n    <values>\n        <INTEGER>1</INTEGER>\n        <INTEGER>2</INTEGER>\n    </values>\n</OptCoords>\n"
        );
        assert_eq!(OptCoords::decode_xer(&xml).unwrap(), c);
    }

    #[test]
    fn optional_seq_of_absent_xer_round_trips_with_no_wrapper() {
        let c = OptCoords { values: None };
        let xml = c.encode_xer();
        // No <values> wrapper at all when absent — not even an empty one.
        assert_eq!(xml, "<OptCoords></OptCoords>\n");
        assert_eq!(OptCoords::decode_xer(&xml).unwrap(), c);
    }

    // ---- SET OF member (gambas-asn1#402) -------

    #[test]
    fn set_of_member_ber_round_trips() {
        let c = SetCoords { values: SetOf(vec![1, 2]) };
        let bytes = c.encode();
        // Outer SEQUENCE (0x30) wraps the member's own SET (0x31 — universal
        // constructed 17, not 0x30/SEQUENCE) of two INTEGER TLVs.
        assert_eq!(
            bytes,
            vec![0x30, 0x08, 0x31, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]
        );
        assert_eq!(SetCoords::decode(&bytes).unwrap(), c);
    }

    #[test]
    fn set_of_member_uses_set_tag_not_sequence_tag() {
        // A member's own encoding must reject a peer struct whose member is
        // SEQUENCE OF (0x30) instead of SET OF (0x31) at the same position
        // — confirms decode actually checks the tag, not just any
        // constructed TLV.
        let coords_bytes = Coords { values: SeqOf(vec![1, 2]) }.encode();
        assert!(SetCoords::decode(&coords_bytes).is_err());
    }

    // ---- SEQUENCE OF/SET OF IMPLICIT tag override -------

    #[test]
    fn tagged_seq_of_uses_the_given_tag_not_the_natural_one() {
        let context_3 = Tag::context(3, true);
        let mut buf = Vec::new();
        encode_seq_of_tagged(&mut buf, context_3, &[1i64, 2i64]);
        // context constructed 3 (0xA3), not 0x30 (universal SEQUENCE).
        assert_eq!(buf, vec![0xA3, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]);
        let mut r = Reader::new(&buf);
        let decoded: Vec<i64> = decode_seq_of_tagged(&mut r, context_3).unwrap();
        assert_eq!(decoded, vec![1, 2]);
    }

    #[test]
    fn tagged_seq_of_rejects_the_natural_tag() {
        let mut buf = Vec::new();
        encode_seq_of(&mut buf, &[1i64]); // natural SEQUENCE_TAG
        let mut r = Reader::new(&buf);
        let result: Result<Vec<i64>, _> = decode_seq_of_tagged(&mut r, Tag::context(3, true));
        assert!(result.is_err());
    }

    #[test]
    fn seq_of_ber_round_trips_through_the_trait() {
        let v = SeqOf(vec![1i64, 2, 3]);
        let mut out = Vec::new();
        v.ber_encode(&mut out);
        assert_eq!(out, vec![0x30, 0x09, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02, 0x02, 0x01, 0x03]);

        let mut r = Reader::new(&out);
        let mut got = SeqOf::<i64>::default();
        got.ber_decode_into(&mut r).unwrap();
        assert_eq!(got, v);
    }

    #[test]
    fn seq_of_xer_round_trips_wrapped_by_hand() {
        let v = SeqOf(vec![1i64, 2]);
        let mut out = String::new();
        crate::xer::write_open_tag(&mut out, "items");
        v.xer_encode(&mut out, 0);
        crate::xer::write_close_tag(&mut out, "items");
        assert_eq!(out, "<items>\n    <INTEGER>1</INTEGER>\n    <INTEGER>2</INTEGER>\n</items>");

        let mut r = XerReader::new(&out);
        r.consume_open_tag("items").unwrap();
        let mut got = SeqOf::<i64>::default();
        got.xer_decode_into(&mut r).unwrap();
        r.consume_close_tag("items").unwrap();
        assert_eq!(got, v);
    }

    #[test]
    fn seq_of_derefs_to_the_inner_vec() {
        let v = SeqOf(vec![1i64, 2, 3]);
        assert_eq!(v.len(), 3);
        assert_eq!(&v[..], &[1, 2, 3]);
    }

    #[test]
    fn set_of_ber_round_trips_through_the_trait_with_its_own_natural_tag() {
        let v = SetOf(vec![1i64, 2]);
        let mut out = Vec::new();
        v.ber_encode(&mut out);
        // SET (0x31 — universal constructed 17), not SEQUENCE (0x30).
        assert_eq!(out, vec![0x31, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]);

        let mut r = Reader::new(&out);
        let mut got = SetOf::<i64>::default();
        got.ber_decode_into(&mut r).unwrap();
        assert_eq!(got, v);
    }

    #[test]
    fn set_of_xer_round_trips_wrapped_by_hand() {
        let v = SetOf(vec![1i64, 2]);
        let mut out = String::new();
        crate::xer::write_open_tag(&mut out, "items");
        v.xer_encode(&mut out, 0);
        crate::xer::write_close_tag(&mut out, "items");
        assert_eq!(out, "<items>\n    <INTEGER>1</INTEGER>\n    <INTEGER>2</INTEGER>\n</items>");

        let mut r = XerReader::new(&out);
        r.consume_open_tag("items").unwrap();
        let mut got = SetOf::<i64>::default();
        got.xer_decode_into(&mut r).unwrap();
        r.consume_close_tag("items").unwrap();
        assert_eq!(got, v);
    }

    #[test]
    fn set_of_derefs_to_the_inner_vec() {
        let v = SetOf(vec![1i64, 2, 3]);
        assert_eq!(v.len(), 3);
        assert_eq!(&v[..], &[1, 2, 3]);
    }

    // ---- DEFAULT-valued member ----------------------------

    #[test]
    fn default_member_present_on_the_wire_uses_its_real_value_not_the_default() {
        let p = DefaultPoint { x: 1, y: Some(7) };
        let decoded = DefaultPoint::decode(&p.encode()).unwrap();
        assert_eq!(decoded, p);
    }

    #[test]
    fn default_member_absent_from_the_wire_gets_the_schema_default_filled_in() {
        // Hand-encode just `x` — same bytes as if `y` had never been
        // written (the real "absent from the wire" case DEFAULT exists for).
        let mut bytes = Vec::new();
        1i64.ber_encode(&mut bytes);
        let mut wire = Vec::new();
        crate::writer::write_constructed(&mut wire, SEQUENCE_TAG, &bytes);

        let decoded = DefaultPoint::decode(&wire).unwrap();
        assert_eq!(decoded, DefaultPoint { x: 1, y: Some(42) });
    }
}
