//! SEQUENCE encode/decode — X.680 §24, X.690 §8.9.
//!
//! Table-driven (gambas-asn1#278), mirroring `SequenceBerHandler`
//! (`runtime/src/BerCodec.cpp`) and `SequenceSpec`/`MemberDescriptor`
//! (`runtime/include/asn1cpp/TypeDescriptor.hpp`): `encode_sequence`/
//! `decode_sequence` are generic, driven entirely by a `SequenceSpec<T>`
//! table — no per-type codegen'd traversal logic, no `switch`/`if` chains.
//! Member access goes through `MemberDescriptor`'s accessor functions
//! (`value.rs`'s module docs explain why every member uses a function, not
//! an `offsetof`-equivalent, unlike the C++ side's required-member fast path).
//!
//! `Point` below is both the worked example and this module's own test
//! subject — it's real, table-driven code (not a stand-in), same role as
//! `test_seq_simple.cpp` on the C++ side and generated by `RustBackend` for
//! real ASN.1 schemas.

use crate::reader::{DecodeError, Reader};
use crate::tag::{universal, Tag};
use crate::value::Asn1Value;
use crate::writer::write_constructed;

pub const SEQUENCE_TAG: Tag = Tag::universal(universal::SEQUENCE, true);

/// One row in a `SequenceSpec<T>` table — mirrors `MemberDescriptor`
/// (`TypeDescriptor.hpp`), minus everything not yet needed by this crate's
/// scope (DEFAULT values, EXPLICIT/IMPLICIT tagging beyond the member's own
/// natural tag, CHOICE alternative dispatch — all real gaps, not silently
/// dropped: `Backend`/codegen simply doesn't emit members needing them yet,
/// same incremental principle as every other gambas-asn1#214 sub-issue).
pub struct MemberDescriptor<T: 'static> {
    pub name: &'static str,
    pub tag: Tag,
    pub optional: bool,
    pub get: fn(&T) -> &dyn Asn1Value,
    pub get_mut: fn(&mut T) -> &mut dyn Asn1Value,
}

/// SEQUENCE/SET member table — mirrors `SequenceSpec` (`TypeDescriptor.hpp`).
///
/// `name` is the XER element tag for the whole SEQUENCE (mirrors
/// `TypeDescriptor::name`, used by `SequenceXerHandler` — X.693's outer
/// element is the *type* name, unlike each member's own tag which is
/// *field*-name-derived). BER doesn't need it (BER dispatch is by `tag`
/// alone), but one table drives both encodings (see `lib.rs`'s XER module
/// doc), so it lives here rather than in a second, XER-only struct.
///
/// **Deliberate layering divergence from both C++ codebases** (checked on
/// review, gambas-asn1#281): in `runtime/include/asn1cpp/TypeDescriptor.hpp`
/// `name` lives on the outer `TypeDescriptor`, a sibling to
/// `sequence_spec`/`choice_spec`/`enum_spec` — never inside `SequenceSpec`
/// itself. Same split in asn1c (`asn_TYPE_descriptor_s::name` vs.
/// `asn_SEQUENCE_specifics_s`, which carries no name at all). That layer
/// exists in both C++ codebases because their dispatch is runtime
/// polymorphic — one `TypeDescriptor*`/`asn_TYPE_descriptor_t*` has to
/// carry `name` regardless of *which* construct (`SEQUENCE`/`CHOICE`/
/// `ENUMERATED`) it points at, since the codec picks the handler at
/// runtime via `TypeKind`/`tag2el`. Rust's design has no such layer:
/// dispatch is by generic parameter (`SequenceSpec<T>`) resolved at compile
/// time, so there is no shared runtime "type descriptor" object for `name`
/// to live on once, and introducing one here would only exist to satisfy
/// field-sharing, not to do anything. Each construct-specific spec (this
/// one; a future `ChoiceSpec<T>` for gambas-asn1#284/#285) carries its own
/// `name` — cheap (`&'static str`, one word, no allocation), and avoids
/// inventing indirection with no other purpose. Documented here so the
/// repetition in the eventual `ChoiceSpec<T>` reads as intentional, not a
/// copy-paste that forgot to deduplicate.
pub struct SequenceSpec<T: 'static> {
    pub name: &'static str,
    pub tag: Tag,
    pub members: &'static [MemberDescriptor<T>],
}

/// Generic SEQUENCE encoder — the Rust analogue of
/// `SequenceBerHandler::encode`. Iterates `spec.members` in order, writing
/// each member's own complete TLV into the constructed SEQUENCE content.
/// OPTIONAL suppression (gambas-asn1#326) needs no special-casing here: an
/// absent `Option<V>::None` member's `ber_encode` (the blanket
/// `Asn1Value for Option<V>` impl, `value.rs`) already writes nothing. No
/// DEFAULT-value suppression yet — a real gap, not silently dropped.
pub fn encode_sequence<T>(spec: &SequenceSpec<T>, value: &T) -> Vec<u8> {
    let mut content = Vec::new();
    for m in spec.members {
        (m.get)(value).ber_encode(&mut content);
    }
    let mut out = Vec::new();
    write_constructed(&mut out, spec.tag, &content);
    out
}

/// Generic SEQUENCE decoder — the Rust analogue of
/// `SequenceBerHandler::decode`/`decode_body`. `T::default()` provides the
/// initial value (matching every generated struct's `#[derive(Default)]`);
/// each member is decoded in table order directly into its field via
/// `ber_decode_into`, no intermediate allocation per member.
///
/// OPTIONAL members (gambas-asn1#326): tag-presence detection, same model
/// `asn1cpp/CLAUDE.md`'s BER-vs-PER table documents ("OPTIONAL detection:
/// Tag present/absent in stream"). Peek before deciding whether to call
/// `ber_decode_into` at all — an absent optional member's tag belongs to
/// whatever comes *next* (the following member, or nothing), so the reader
/// must not be advanced past it if this member isn't present. Only a linear
/// scan (each optional member checked once, in table order) — correct for
/// SEQUENCE's canonical member ordering (X.690 §8.9), same simplifying
/// assumption `MemberDescriptor`'s module doc already documents this crate
/// making elsewhere (no DEFAULT values, no out-of-order OPTIONAL members).
pub fn decode_sequence<T: Default>(spec: &SequenceSpec<T>, data: &[u8]) -> Result<T, DecodeError> {
    let mut r = Reader::new(data);
    let tlv = r.read_tlv()?;
    if tlv.tag != spec.tag {
        return Err(DecodeError::new(format!("expected SEQUENCE tag, got {:?}", tlv.tag), r.pos()));
    }
    let mut inner = Reader::new(tlv.value);
    let mut result = T::default();
    for m in spec.members {
        if m.optional {
            if inner.peek_tag() == Some(m.tag) {
                (m.get_mut)(&mut result).ber_decode_into(&mut inner)?;
            }
        } else {
            (m.get_mut)(&mut result).ber_decode_into(&mut inner)?;
        }
    }
    Ok(result)
}

/// `Point ::= SEQUENCE { x INTEGER, y INTEGER }`
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Point {
    pub x: i64,
    pub y: i64,
}

static POINT_MEMBERS: [MemberDescriptor<Point>; 2] = [
    MemberDescriptor {
        name: "x",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        get: |v| &v.x,
        get_mut: |v| &mut v.x,
    },
    MemberDescriptor {
        name: "y",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        get: |v| &v.y,
        get_mut: |v| &mut v.y,
    },
];

static POINT_SPEC: SequenceSpec<Point> =
    SequenceSpec { name: "Point", tag: SEQUENCE_TAG, members: &POINT_MEMBERS };

impl Point {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&POINT_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<Point, DecodeError> {
        decode_sequence(&POINT_SPEC, data)
    }

    pub fn encode_xer(&self) -> String {
        crate::xer::encode_sequence_xer(&POINT_SPEC, self)
    }

    pub fn decode_xer(xml: &str) -> Result<Point, DecodeError> {
        crate::xer::decode_sequence_xer(&POINT_SPEC, xml)
    }
}

/// `OptPoint ::= SEQUENCE { x INTEGER, y INTEGER OPTIONAL }` — worked
/// example + test subject for OPTIONAL member support (gambas-asn1#326),
/// same role `Point` plays for required-only members.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct OptPoint {
    pub x: i64,
    pub y: Option<i64>,
}

static OPT_POINT_MEMBERS: [MemberDescriptor<OptPoint>; 2] = [
    MemberDescriptor {
        name: "x",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        get: |v| &v.x,
        get_mut: |v| &mut v.x,
    },
    MemberDescriptor {
        name: "y",
        tag: crate::integer::INTEGER_TAG,
        optional: true,
        get: |v| &v.y,
        get_mut: |v| &mut v.y,
    },
];

static OPT_POINT_SPEC: SequenceSpec<OptPoint> =
    SequenceSpec { name: "OptPoint", tag: SEQUENCE_TAG, members: &OPT_POINT_MEMBERS };

impl OptPoint {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&OPT_POINT_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<OptPoint, DecodeError> {
        decode_sequence(&OPT_POINT_SPEC, data)
    }

    pub fn encode_xer(&self) -> String {
        crate::xer::encode_sequence_xer(&OPT_POINT_SPEC, self)
    }

    pub fn decode_xer(xml: &str) -> Result<OptPoint, DecodeError> {
        crate::xer::decode_sequence_xer(&OPT_POINT_SPEC, xml)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encodes_hand_computed_vector() {
        let p = Point { x: 1, y: 2 };
        // SEQUENCE (0x30), length 6, then two INTEGER TLVs (0x02 0x01 0x01, 0x02 0x01 0x02).
        assert_eq!(
            p.encode(),
            vec![0x30, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]
        );
    }

    #[test]
    fn round_trips() {
        let p = Point { x: -5, y: 300 };
        let bytes = p.encode();
        assert_eq!(Point::decode(&bytes).unwrap(), p);
    }

    #[test]
    fn wrong_tag_is_error() {
        let data = [0x02, 0x01, 0x05]; // INTEGER tag, not SEQUENCE
        assert!(Point::decode(&data).is_err());
    }

    #[test]
    fn truncated_second_field_is_error() {
        // SEQUENCE containing only one INTEGER, second read must fail.
        let data = [0x30, 0x03, 0x02, 0x01, 0x01];
        assert!(Point::decode(&data).is_err());
    }

    #[test]
    fn xer_encodes_hand_computed_vector() {
        // Matches SequenceXerHandler's output shape (runtime/src/XerCodec.cpp):
        // <Point>\n    <x>3</x>\n    <y>4</y>\n</Point>\n
        let p = Point { x: 3, y: 4 };
        assert_eq!(p.encode_xer(), "<Point>\n    <x>3</x>\n    <y>4</y>\n</Point>\n");
    }

    #[test]
    fn xer_round_trips() {
        let p = Point { x: -5, y: 300 };
        let xml = p.encode_xer();
        assert_eq!(Point::decode_xer(&xml).unwrap(), p);
    }

    #[test]
    fn xer_zero_round_trips() {
        let p = Point { x: 0, y: 0 };
        let xml = p.encode_xer();
        assert_eq!(xml, "<Point>\n    <x>0</x>\n    <y>0</y>\n</Point>\n");
        assert_eq!(Point::decode_xer(&xml).unwrap(), p);
    }

    #[test]
    fn xer_wrong_outer_tag_is_error() {
        assert!(Point::decode_xer("<NotPoint><x>1</x><y>2</y></NotPoint>").is_err());
    }

    #[test]
    fn xer_truncated_is_error() {
        assert!(Point::decode_xer("<Point>\n    <x>3</x>\n</Point>\n").is_err());
    }

    // ---- OPTIONAL member support (gambas-asn1#326) -------------------------

    #[test]
    fn opt_present_ber_round_trips() {
        let p = OptPoint { x: 1, y: Some(2) };
        let bytes = p.encode();
        assert_eq!(bytes, vec![0x30, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]);
        assert_eq!(OptPoint::decode(&bytes).unwrap(), p);
    }

    #[test]
    fn opt_absent_ber_round_trips() {
        let p = OptPoint { x: 1, y: None };
        let bytes = p.encode();
        // Only the required member's TLV — no trace of y at all.
        assert_eq!(bytes, vec![0x30, 0x03, 0x02, 0x01, 0x01]);
        assert_eq!(OptPoint::decode(&bytes).unwrap(), p);
    }

    #[test]
    fn opt_present_xer_round_trips() {
        let p = OptPoint { x: 1, y: Some(2) };
        let xml = p.encode_xer();
        assert_eq!(xml, "<OptPoint>\n    <x>1</x>\n    <y>2</y>\n</OptPoint>\n");
        assert_eq!(OptPoint::decode_xer(&xml).unwrap(), p);
    }

    #[test]
    fn opt_absent_xer_round_trips() {
        let p = OptPoint { x: 1, y: None };
        let xml = p.encode_xer();
        // No <y> element at all when absent.
        assert_eq!(xml, "<OptPoint>\n    <x>1</x>\n</OptPoint>\n");
        assert_eq!(OptPoint::decode_xer(&xml).unwrap(), p);
    }
}
