//! SEQUENCE encode/decode — X.680 §24, X.690 §8.9.
//!
//! Table-driven (gambas-asn1#278), mirroring `SequenceBerHandler`
//! (`runtime/src/BerCodec.cpp`) and `SequenceSpec`/`MemberDescriptor`
//! (`runtime/include/asn1cpp/TypeDescriptor.hpp`): `encode_sequence`/
//! `decode_sequence` are generic, driven entirely by a `SequenceSpec<T>`
//! table — no per-type codegen'd traversal logic, no `switch`/`if` chains.
//! Member access goes through `MemberDescriptor`'s accessor functions
//! (`value.rs`'s module docs explain why every member uses a function, not
//! an `offsetof`-equivalent, unlike the C++ side's required-member fast path).
//!
//! `Point` below is both the worked example and this module's own test
//! subject — it's real, table-driven code (not a stand-in), same role as
//! `test_seq_simple.cpp` on the C++ side and generated by `RustBackend` for
//! real ASN.1 schemas.

use crate::reader::{DecodeError, Reader};
use crate::tag::{universal, Tag};
use crate::value::Asn1Value;
use crate::writer::write_constructed;

pub const SEQUENCE_TAG: Tag = Tag::universal(universal::SEQUENCE, true);

/// One row in a `SequenceSpec<T>` table — mirrors `MemberDescriptor`
/// (`TypeDescriptor.hpp`), minus everything not yet needed by this crate's
/// scope (DEFAULT values, EXPLICIT/IMPLICIT tagging beyond the member's own
/// natural tag, CHOICE alternative dispatch — all real gaps, not silently
/// dropped: `Backend`/codegen simply doesn't emit members needing them yet,
/// same incremental principle as every other gambas-asn1#214 sub-issue).
pub struct MemberDescriptor<T: 'static> {
    pub name: &'static str,
    pub tag: Tag,
    pub optional: bool,
    pub get: fn(&T) -> &dyn Asn1Value,
    pub get_mut: fn(&mut T) -> &mut dyn Asn1Value,
}

/// SEQUENCE/SET member table — mirrors `SequenceSpec` (`TypeDescriptor.hpp`).
pub struct SequenceSpec<T: 'static> {
    pub tag: Tag,
    pub members: &'static [MemberDescriptor<T>],
}

/// Generic SEQUENCE encoder — the Rust analogue of
/// `SequenceBerHandler::encode`. Iterates `spec.members` in order, writing
/// each member's own complete TLV into the constructed SEQUENCE content.
/// No OPTIONAL/DEFAULT suppression yet (`MemberDescriptor::optional` is
/// carried in the table already, ready for that once decode needs it too —
/// see the module doc's scope note).
pub fn encode_sequence<T>(spec: &SequenceSpec<T>, value: &T) -> Vec<u8> {
    let mut content = Vec::new();
    for m in spec.members {
        (m.get)(value).ber_encode(&mut content);
    }
    let mut out = Vec::new();
    write_constructed(&mut out, spec.tag, &content);
    out
}

/// Generic SEQUENCE decoder — the Rust analogue of
/// `SequenceBerHandler::decode`/`decode_body`. `T::default()` provides the
/// initial value (matching every generated struct's `#[derive(Default)]`);
/// each member is decoded in table order directly into its field via
/// `ber_decode_into`, no intermediate allocation per member.
pub fn decode_sequence<T: Default>(spec: &SequenceSpec<T>, data: &[u8]) -> Result<T, DecodeError> {
    let mut r = Reader::new(data);
    let tlv = r.read_tlv()?;
    if tlv.tag != spec.tag {
        return Err(DecodeError::new(format!("expected SEQUENCE tag, got {:?}", tlv.tag), r.pos()));
    }
    let mut inner = Reader::new(tlv.value);
    let mut result = T::default();
    for m in spec.members {
        (m.get_mut)(&mut result).ber_decode_into(&mut inner)?;
    }
    Ok(result)
}

/// `Point ::= SEQUENCE { x INTEGER, y INTEGER }`
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub struct Point {
    pub x: i64,
    pub y: i64,
}

static POINT_MEMBERS: [MemberDescriptor<Point>; 2] = [
    MemberDescriptor {
        name: "x",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        get: |v| &v.x,
        get_mut: |v| &mut v.x,
    },
    MemberDescriptor {
        name: "y",
        tag: crate::integer::INTEGER_TAG,
        optional: false,
        get: |v| &v.y,
        get_mut: |v| &mut v.y,
    },
];

static POINT_SPEC: SequenceSpec<Point> = SequenceSpec { tag: SEQUENCE_TAG, members: &POINT_MEMBERS };

impl Point {
    pub fn encode(&self) -> Vec<u8> {
        encode_sequence(&POINT_SPEC, self)
    }

    pub fn decode(data: &[u8]) -> Result<Point, DecodeError> {
        decode_sequence(&POINT_SPEC, data)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn encodes_hand_computed_vector() {
        let p = Point { x: 1, y: 2 };
        // SEQUENCE (0x30), length 6, then two INTEGER TLVs (0x02 0x01 0x01, 0x02 0x01 0x02).
        assert_eq!(
            p.encode(),
            vec![0x30, 0x06, 0x02, 0x01, 0x01, 0x02, 0x01, 0x02]
        );
    }

    #[test]
    fn round_trips() {
        let p = Point { x: -5, y: 300 };
        let bytes = p.encode();
        assert_eq!(Point::decode(&bytes).unwrap(), p);
    }

    #[test]
    fn wrong_tag_is_error() {
        let data = [0x02, 0x01, 0x05]; // INTEGER tag, not SEQUENCE
        assert!(Point::decode(&data).is_err());
    }

    #[test]
    fn truncated_second_field_is_error() {
        // SEQUENCE containing only one INTEGER, second read must fail.
        let data = [0x30, 0x03, 0x02, 0x01, 0x01];
        assert!(Point::decode(&data).is_err());
    }
}
