#include <iostream>
#include <fstream>
#include <string>
#include <vector>
#include <filesystem>
#include <cstdlib>
#include <getopt.h>
#include <reflex/input.h>

#include "Lexer.hpp"      // in build/compiler/ (generated) or grammar/ (wrapper)
#include "asn1.tab.hh"   // generated by Bison into build/compiler/
#include "ast/Module.hpp"
#include "sema/Resolver.hpp"
#include "codegen/Generator.hpp"

namespace fs = std::filesystem;

static const struct option long_opts[] = {
    {"help",                 no_argument,       nullptr, 'h'},
    {"fallow-newer-modules", no_argument,       nullptr, 'A'},
    {"fbless-SIZE",          no_argument,       nullptr, 'B'},
    {"fprefix",              required_argument, nullptr, 'P'},
    {"integer-type",         required_argument, nullptr, 'I'},
    {nullptr, 0, nullptr, 0}
};

static void print_help(const char* prog) {
    std::cout <<
        "Usage: " << prog << " [options] file.asn1 [file2.asn1 ...]\n"
        "\n"
        "Options:\n"
        "  -h, --help                  Show this help and exit\n"
        "  -E                          Parse and check only; skip code generation\n"
        "  -o <dir>                    Output directory (default: generated)\n"
        "  -fallow-newer-modules       Accept module version mismatches silently\n"
        "  -fbless-SIZE                (Non-standard) Accept SIZE() on INTEGER/ENUMERATED\n"
        "  -fprefix=<name>             Wrap all generated types in namespace <name>.\n"
        "                              (asn1c compatibility flag — asn1c prepends <name>\n"
        "                              as a C identifier prefix; asn1cpp uses a C++ namespace\n"
        "                              instead, which is idiomatic and collision-safe.)\n"
        "  --integer-type=<kind>       Integer storage: int64 (default), uint64,\n"
        "                              int128 (unimplemented), arbitrary (unimplemented)\n";
}

static void usage(const char* prog) {
    std::cerr << "Usage: " << prog
              << " [-E] [-o outdir] [-fallow-newer-modules] [-fbless-SIZE]"
                 " [-fprefix=<name>]"
                 " [--integer-type=int64|uint64|int128|arbitrary]"
                 " file.asn1 [file2.asn1 ...]\n"
                 "Try '" << prog << " --help' for more information.\n";
    std::exit(1);
}

int main(int argc, char** argv) {
    std::string out_dir = "generated";
    std::string ns_prefix;
    bool allow_newer_modules = false;
    bool bless_size = false;
    bool parse_only = false;
    asn1::codegen::IntStorageKind default_int_kind = asn1::codegen::IntStorageKind::S64;
    std::vector<std::string> input_files;

    int opt;
    opterr = 0;  // suppress getopt's own diagnostics; usage() handles all errors
    while ((opt = getopt_long_only(argc, argv, "Eo:h", long_opts, nullptr)) != -1) {
        switch (opt) {
        case 'E': parse_only = true; break;
        case 'o': out_dir = optarg; break;
        case 'h': print_help(argv[0]); return 0;
        case 'A': allow_newer_modules = true; break;
        case 'P': ns_prefix = optarg; break;
        case 'B':
            // Non-standard: accept SIZE() on INTEGER/ENUMERATED (asn1c compatibility).
            // X.680 §47.5.2 forbids this; the constraint is silently ignored in codegen.
            bless_size = true;
            break;
        case 'I': {
            std::string kind = optarg;
            if (kind == "int64") {
                default_int_kind = asn1::codegen::IntStorageKind::S64;
            } else if (kind == "uint64") {
                default_int_kind = asn1::codegen::IntStorageKind::U64;
            } else if (kind == "int128") {
                std::cerr << "warning: --integer-type=int128 is not yet implemented; using int64\n";
            } else if (kind == "arbitrary") {
                std::cerr << "warning: --integer-type=arbitrary is not yet implemented; using int64\n";
            } else {
                std::cerr << "error: unknown --integer-type value '" << kind << "'\n";
                usage(argv[0]);
            }
            break;
        }
        default: usage(argv[0]);
        }
    }
    for (int i = optind; i < argc; ++i)
        input_files.push_back(argv[i]);
    if (input_files.empty()) usage(argv[0]);

    if (!ns_prefix.empty()) {
        auto valid_id = [](std::string_view s) {
            if (s.empty()) return false;
            if (!std::isalpha((unsigned char)s[0]) && s[0] != '_') return false;
            return std::all_of(s.begin(), s.end(), [](char c){
                return std::isalnum((unsigned char)c) || c == '_';
            });
        };
        if (!valid_id(ns_prefix)) {
            std::cerr << "error: -fprefix value '" << ns_prefix << "' is not a valid C++ identifier\n";
            return 1;
        }
    }

    asn1::ast::ParseResult pr;

    for (const auto& path : input_files) {
        std::ifstream in(path);
        if (!in) {
            std::cerr << "Cannot open " << path << "\n";
            return 1;
        }
        std::string src((std::istreambuf_iterator<char>(in)),
                         std::istreambuf_iterator<char>());

        Lexer lexer(reflex::Input(src), std::cerr);
        yy::parser parser(lexer, pr);
        if (parser.parse() != 0) {
            std::cerr << "Parse error in " << path << "\n";
            return 1;
        }
    }

    std::cout << "Parsed " << pr.modules.size() << " module(s).\n";
    for (const auto& mod : pr.modules)
        std::cout << "  Module: " << mod->name
                  << " (" << mod->assignments.size() << " assignments)\n";

    if (parse_only)
        return 0;

    asn1::sema::Resolver resolver;
    resolver.set_allow_newer_modules(allow_newer_modules);
    resolver.set_bless_size(bless_size);
    resolver.collect(pr);
    resolver.resolve_imports(pr);
    resolver.resolve_types(pr);
    resolver.resolve_value_assignments(pr);

    for (const auto& w : resolver.warnings())
        std::cerr << "warning: " << w << "\n";
    if (!resolver.errors().empty()) {
        for (const auto& e : resolver.errors())
            std::cerr << "error: " << e << "\n";
        return 1;
    }

    asn1::codegen::Generator gen(out_dir, resolver);
    gen.set_default_int_kind(default_int_kind);
    if (!ns_prefix.empty()) gen.set_namespace(ns_prefix);
    gen.generate(pr);

    std::cout << "Generated C++ code in: " << out_dir << "/\n";
    return 0;
}
