/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "EpsHI2Operations"
 * 	found in "asn1-files/133108/EpsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "EpsHI2Operations_MediaDecryption-info.h"

#include "EpsHI2Operations_CCKeyInfo.h"
asn_TYPE_member_t asn_MBR_EpsHI2Operations_MediaDecryption_info_1[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EpsHI2Operations_CCKeyInfo,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_EpsHI2Operations_MediaDecryption_info_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
asn_SET_OF_specifics_t asn_SPC_EpsHI2Operations_MediaDecryption_info_specs_1 = {
	sizeof(struct EpsHI2Operations_MediaDecryption_info),
	offsetof(struct EpsHI2Operations_MediaDecryption_info, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
asn_TYPE_descriptor_t asn_DEF_EpsHI2Operations_MediaDecryption_info = {
	"MediaDecryption-info",
	"MediaDecryption-info",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_EpsHI2Operations_MediaDecryption_info_tags_1,
	sizeof(asn_DEF_EpsHI2Operations_MediaDecryption_info_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_MediaDecryption_info_tags_1[0]), /* 1 */
	asn_DEF_EpsHI2Operations_MediaDecryption_info_tags_1,	/* Same as above */
	sizeof(asn_DEF_EpsHI2Operations_MediaDecryption_info_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_MediaDecryption_info_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_OF_constraint
	},
	asn_MBR_EpsHI2Operations_MediaDecryption_info_1,
	1,	/* Single element */
	&asn_SPC_EpsHI2Operations_MediaDecryption_info_specs_1	/* Additional specs */
};

