/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "EpsHI2Operations"
 * 	found in "asn1-files/133108/EpsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "EpsHI2Operations_MapDatum.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_EpsHI2Operations_MapDatum_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_EpsHI2Operations_MapDatum_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_EpsHI2Operations_MapDatum_value2enum_1[] = {
	{ 0,	5,	"wGS84" },
	{ 1,	5,	"wGS72" },
	{ 2,	4,	"eD50" }
	/* This list is extensible */
};
static int asn_validate_EpsHI2Operations_MapDatum_1(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_EpsHI2Operations_MapDatum value = *(e_EpsHI2Operations_MapDatum*)sptr;
    switch(value) {
    case EpsHI2Operations_MapDatum_wGS84:
    case EpsHI2Operations_MapDatum_wGS72:
    case EpsHI2Operations_MapDatum_eD50:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_EpsHI2Operations_MapDatum_enum2value_1[] = {
	2,	/* eD50(2) */
	1,	/* wGS72(1) */
	0	/* wGS84(0) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_EpsHI2Operations_MapDatum_specs_1 = {
	asn_MAP_EpsHI2Operations_MapDatum_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_EpsHI2Operations_MapDatum_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	4,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_EpsHI2Operations_MapDatum_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_EpsHI2Operations_MapDatum = {
	"MapDatum",
	"MapDatum",
	&asn_OP_NativeEnumerated,
	asn_DEF_EpsHI2Operations_MapDatum_tags_1,
	sizeof(asn_DEF_EpsHI2Operations_MapDatum_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_MapDatum_tags_1[0]), /* 1 */
	asn_DEF_EpsHI2Operations_MapDatum_tags_1,	/* Same as above */
	sizeof(asn_DEF_EpsHI2Operations_MapDatum_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_MapDatum_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_EpsHI2Operations_MapDatum_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_EpsHI2Operations_MapDatum_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_EpsHI2Operations_MapDatum_1
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_EpsHI2Operations_MapDatum_specs_1	/* Additional specs */
};

