/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "EpsHI2Operations"
 * 	found in "asn1-files/133108/EpsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "EpsHI2Operations_PANI-Header-Info.h"

#include "EpsHI2Operations_PANI-Location.h"
asn_TYPE_member_t asn_MBR_EpsHI2Operations_PANI_Header_Info_1[] = {
	{ ATF_POINTER, 4, offsetof(struct EpsHI2Operations_PANI_Header_Info, access_Type),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"access-Type"
		},
	{ ATF_POINTER, 3, offsetof(struct EpsHI2Operations_PANI_Header_Info, access_Class),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"access-Class"
		},
	{ ATF_POINTER, 2, offsetof(struct EpsHI2Operations_PANI_Header_Info, network_Provided),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NULL,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"network-Provided"
		},
	{ ATF_POINTER, 1, offsetof(struct EpsHI2Operations_PANI_Header_Info, pANI_Location),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EpsHI2Operations_PANI_Location,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"pANI-Location"
		},
};
static const int asn_MAP_EpsHI2Operations_PANI_Header_Info_oms_1[] = { 0, 1, 2, 3 };
static const ber_tlv_tag_t asn_DEF_EpsHI2Operations_PANI_Header_Info_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EpsHI2Operations_PANI_Header_Info_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* access-Type */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* access-Class */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* network-Provided */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 } /* pANI-Location */
};
asn_SEQUENCE_specifics_t asn_SPC_EpsHI2Operations_PANI_Header_Info_specs_1 = {
	sizeof(struct EpsHI2Operations_PANI_Header_Info),
	offsetof(struct EpsHI2Operations_PANI_Header_Info, _asn_ctx),
	asn_MAP_EpsHI2Operations_PANI_Header_Info_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_EpsHI2Operations_PANI_Header_Info_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EpsHI2Operations_PANI_Header_Info = {
	"PANI-Header-Info",
	"PANI-Header-Info",
	&asn_OP_SEQUENCE,
	asn_DEF_EpsHI2Operations_PANI_Header_Info_tags_1,
	sizeof(asn_DEF_EpsHI2Operations_PANI_Header_Info_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_PANI_Header_Info_tags_1[0]), /* 1 */
	asn_DEF_EpsHI2Operations_PANI_Header_Info_tags_1,	/* Same as above */
	sizeof(asn_DEF_EpsHI2Operations_PANI_Header_Info_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_PANI_Header_Info_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_EpsHI2Operations_PANI_Header_Info_1,
	4,	/* Elements count */
	&asn_SPC_EpsHI2Operations_PANI_Header_Info_specs_1	/* Additional specs */
};

