/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "EpsHI2Operations"
 * 	found in "asn1-files/133108/EpsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "EpsHI2Operations_UmtsQos.h"

#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_EpsHI2Operations_UmtsQos_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_EpsHI2Operations_UmtsQos_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 1,  1,  0,  1 }	/* (0..1) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_EpsHI2Operations_UmtsQos_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct EpsHI2Operations_UmtsQos, choice.qosMobileRadio),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"qosMobileRadio"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct EpsHI2Operations_UmtsQos, choice.qosGn),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"qosGn"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_EpsHI2Operations_UmtsQos_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* qosMobileRadio */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* qosGn */
};
asn_CHOICE_specifics_t asn_SPC_EpsHI2Operations_UmtsQos_specs_1 = {
	sizeof(struct EpsHI2Operations_UmtsQos),
	offsetof(struct EpsHI2Operations_UmtsQos, _asn_ctx),
	offsetof(struct EpsHI2Operations_UmtsQos, present),
	sizeof(((struct EpsHI2Operations_UmtsQos *)0)->present),
	asn_MAP_EpsHI2Operations_UmtsQos_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	-1	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_EpsHI2Operations_UmtsQos = {
	"UmtsQos",
	"UmtsQos",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_EpsHI2Operations_UmtsQos_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_EpsHI2Operations_UmtsQos_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_EpsHI2Operations_UmtsQos_1,
	2,	/* Elements count */
	&asn_SPC_EpsHI2Operations_UmtsQos_specs_1	/* Additional specs */
};

