/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "EpsHI2Operations"
 * 	found in "asn1-files/133108/EpsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "EpsHI2Operations_IMSevent.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_EpsHI2Operations_IMSevent_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_EpsHI2Operations_IMSevent_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  0,  0,  0,  0 }	/* (0..0,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_EpsHI2Operations_IMSevent_value2enum_1[] = {
	{ 1,	20,	"unfilteredSIPmessage" },
	{ 2,	13,	"sIPheaderOnly" },
	{ 3,	23,	"decryptionKeysAvailable" },
	{ 4,	43,	"startOfInterceptionForIMSEstablishedSession" },
	{ 5,	11,	"xCAPRequest" },
	{ 6,	12,	"xCAPResponse" },
	{ 7,	13,	"ccUnavailable" },
	{ 8,	10,	"sMSOverIMS" },
	{ 9,	13,	"servingSystem" },
	{ 10,	22,	"subscriberRecordChange" },
	{ 11,	23,	"registrationTermination" },
	{ 12,	26,	"locationInformationRequest" }
	/* This list is extensible */
};
static int asn_validate_EpsHI2Operations_IMSevent_1(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_EpsHI2Operations_IMSevent value = *(e_EpsHI2Operations_IMSevent*)sptr;
    switch(value) {
    case EpsHI2Operations_IMSevent_unfilteredSIPmessage:
    case EpsHI2Operations_IMSevent_sIPheaderOnly:
    case EpsHI2Operations_IMSevent_decryptionKeysAvailable:
    case EpsHI2Operations_IMSevent_startOfInterceptionForIMSEstablishedSession:
    case EpsHI2Operations_IMSevent_xCAPRequest:
    case EpsHI2Operations_IMSevent_xCAPResponse:
    case EpsHI2Operations_IMSevent_ccUnavailable:
    case EpsHI2Operations_IMSevent_sMSOverIMS:
    case EpsHI2Operations_IMSevent_servingSystem:
    case EpsHI2Operations_IMSevent_subscriberRecordChange:
    case EpsHI2Operations_IMSevent_registrationTermination:
    case EpsHI2Operations_IMSevent_locationInformationRequest:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_EpsHI2Operations_IMSevent_enum2value_1[] = {
	6,	/* ccUnavailable(7) */
	2,	/* decryptionKeysAvailable(3) */
	11,	/* locationInformationRequest(12) */
	10,	/* registrationTermination(11) */
	1,	/* sIPheaderOnly(2) */
	7,	/* sMSOverIMS(8) */
	8,	/* servingSystem(9) */
	3,	/* startOfInterceptionForIMSEstablishedSession(4) */
	9,	/* subscriberRecordChange(10) */
	0,	/* unfilteredSIPmessage(1) */
	4,	/* xCAPRequest(5) */
	5	/* xCAPResponse(6) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_EpsHI2Operations_IMSevent_specs_1 = {
	asn_MAP_EpsHI2Operations_IMSevent_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_EpsHI2Operations_IMSevent_enum2value_1,	/* N => "tag"; sorted by N */
	12,	/* Number of elements in the maps */
	2,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_EpsHI2Operations_IMSevent_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_EpsHI2Operations_IMSevent = {
	"IMSevent",
	"IMSevent",
	&asn_OP_NativeEnumerated,
	asn_DEF_EpsHI2Operations_IMSevent_tags_1,
	sizeof(asn_DEF_EpsHI2Operations_IMSevent_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_IMSevent_tags_1[0]), /* 1 */
	asn_DEF_EpsHI2Operations_IMSevent_tags_1,	/* Same as above */
	sizeof(asn_DEF_EpsHI2Operations_IMSevent_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_IMSevent_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_EpsHI2Operations_IMSevent_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_EpsHI2Operations_IMSevent_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_EpsHI2Operations_IMSevent_1
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_EpsHI2Operations_IMSevent_specs_1	/* Additional specs */
};

