/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "EpsHI2Operations"
 * 	found in "asn1-files/133108/EpsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "EpsHI2Operations_GA-Point.h"

#include "EpsHI2Operations_GeographicalCoordinates.h"
asn_TYPE_member_t asn_MBR_EpsHI2Operations_GA_Point_1[] = {
	{ ATF_POINTER, 0, offsetof(struct EpsHI2Operations_GA_Point, geographicalCoordinates),
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_EpsHI2Operations_GeographicalCoordinates,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"geographicalCoordinates"
		},
};
static const ber_tlv_tag_t asn_DEF_EpsHI2Operations_GA_Point_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_EpsHI2Operations_GA_Point_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (16 << 2)), 0, 0, 0 } /* geographicalCoordinates */
};
asn_SEQUENCE_specifics_t asn_SPC_EpsHI2Operations_GA_Point_specs_1 = {
	sizeof(struct EpsHI2Operations_GA_Point),
	offsetof(struct EpsHI2Operations_GA_Point, _asn_ctx),
	asn_MAP_EpsHI2Operations_GA_Point_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_EpsHI2Operations_GA_Point = {
	"GA-Point",
	"GA-Point",
	&asn_OP_SEQUENCE,
	asn_DEF_EpsHI2Operations_GA_Point_tags_1,
	sizeof(asn_DEF_EpsHI2Operations_GA_Point_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_GA_Point_tags_1[0]), /* 1 */
	asn_DEF_EpsHI2Operations_GA_Point_tags_1,	/* Same as above */
	sizeof(asn_DEF_EpsHI2Operations_GA_Point_tags_1)
		/sizeof(asn_DEF_EpsHI2Operations_GA_Point_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_EpsHI2Operations_GA_Point_1,
	1,	/* Elements count */
	&asn_SPC_EpsHI2Operations_GA_Point_specs_1	/* Additional specs */
};

