/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "HI2Operations"
 * 	found in "asn1-files/102232-1/HI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "HI2Operations_CommunicationIdentifier.h"

#include "Network-Identifier.h"
static int
memb_communication_Identity_Number_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1UL && size <= 8UL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_communication_Identity_Number_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..8)) */};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_communication_Identity_Number_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 3,  3,  1,  8 }	/* (SIZE(1..8)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_HI2Operations_CommunicationIdentifier_1[] = {
	{ ATF_POINTER, 1, offsetof(struct HI2Operations_CommunicationIdentifier, communication_Identity_Number),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_communication_Identity_Number_constr_2,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_communication_Identity_Number_constr_2,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_communication_Identity_Number_constraint_1
		},
		0, 0, /* No default value */
		"communication-Identity-Number"
		},
	{ ATF_POINTER, 0, offsetof(struct HI2Operations_CommunicationIdentifier, network_Identifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_Network_Identifier,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"network-Identifier"
		},
};
static const int asn_MAP_HI2Operations_CommunicationIdentifier_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_HI2Operations_CommunicationIdentifier_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_HI2Operations_CommunicationIdentifier_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* communication-Identity-Number */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* network-Identifier */
};
asn_SEQUENCE_specifics_t asn_SPC_HI2Operations_CommunicationIdentifier_specs_1 = {
	sizeof(struct HI2Operations_CommunicationIdentifier),
	offsetof(struct HI2Operations_CommunicationIdentifier, _asn_ctx),
	asn_MAP_HI2Operations_CommunicationIdentifier_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_HI2Operations_CommunicationIdentifier_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_HI2Operations_CommunicationIdentifier = {
	"CommunicationIdentifier",
	"CommunicationIdentifier",
	&asn_OP_SEQUENCE,
	asn_DEF_HI2Operations_CommunicationIdentifier_tags_1,
	sizeof(asn_DEF_HI2Operations_CommunicationIdentifier_tags_1)
		/sizeof(asn_DEF_HI2Operations_CommunicationIdentifier_tags_1[0]), /* 1 */
	asn_DEF_HI2Operations_CommunicationIdentifier_tags_1,	/* Same as above */
	sizeof(asn_DEF_HI2Operations_CommunicationIdentifier_tags_1)
		/sizeof(asn_DEF_HI2Operations_CommunicationIdentifier_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_HI2Operations_CommunicationIdentifier_1,
	2,	/* Elements count */
	&asn_SPC_HI2Operations_CommunicationIdentifier_specs_1	/* Additional specs */
};

