/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "IWLANUmtsHI2Operations"
 * 	found in "asn1-files/133108/IWLANUmtsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "IWLANUmtsHI2Operations_Services-Data-Information.h"

#include "I-WLAN-parameters.h"
asn_TYPE_member_t asn_MBR_IWLANUmtsHI2Operations_Services_Data_Information_1[] = {
	{ ATF_POINTER, 1, offsetof(struct IWLANUmtsHI2Operations_Services_Data_Information, i_WLAN_parameters),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_I_WLAN_parameters,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"i-WLAN-parameters"
		},
};
static const int asn_MAP_IWLANUmtsHI2Operations_Services_Data_Information_oms_1[] = { 0 };
static const ber_tlv_tag_t asn_DEF_IWLANUmtsHI2Operations_Services_Data_Information_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_IWLANUmtsHI2Operations_Services_Data_Information_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 } /* i-WLAN-parameters */
};
asn_SEQUENCE_specifics_t asn_SPC_IWLANUmtsHI2Operations_Services_Data_Information_specs_1 = {
	sizeof(struct IWLANUmtsHI2Operations_Services_Data_Information),
	offsetof(struct IWLANUmtsHI2Operations_Services_Data_Information, _asn_ctx),
	asn_MAP_IWLANUmtsHI2Operations_Services_Data_Information_tag2el_1,
	1,	/* Count of tags in the map */
	asn_MAP_IWLANUmtsHI2Operations_Services_Data_Information_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_IWLANUmtsHI2Operations_Services_Data_Information = {
	"Services-Data-Information",
	"Services-Data-Information",
	&asn_OP_SEQUENCE,
	asn_DEF_IWLANUmtsHI2Operations_Services_Data_Information_tags_1,
	sizeof(asn_DEF_IWLANUmtsHI2Operations_Services_Data_Information_tags_1)
		/sizeof(asn_DEF_IWLANUmtsHI2Operations_Services_Data_Information_tags_1[0]), /* 1 */
	asn_DEF_IWLANUmtsHI2Operations_Services_Data_Information_tags_1,	/* Same as above */
	sizeof(asn_DEF_IWLANUmtsHI2Operations_Services_Data_Information_tags_1)
		/sizeof(asn_DEF_IWLANUmtsHI2Operations_Services_Data_Information_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_IWLANUmtsHI2Operations_Services_Data_Information_1,
	1,	/* Elements count */
	&asn_SPC_IWLANUmtsHI2Operations_Services_Data_Information_specs_1	/* Additional specs */
};

