/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "IWLANUmtsHI2Operations"
 * 	found in "asn1-files/133108/IWLANUmtsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "IWLANUmtsHI2Operations_VisitedPLMNID.h"

/*
 * This type is implemented using OCTET_STRING,
 * so here we adjust the DEF accordingly.
 */
static const ber_tlv_tag_t asn_DEF_IWLANUmtsHI2Operations_VisitedPLMNID_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (4 << 2))
};
asn_TYPE_descriptor_t asn_DEF_IWLANUmtsHI2Operations_VisitedPLMNID = {
	"VisitedPLMNID",
	"VisitedPLMNID",
	&asn_OP_OCTET_STRING,
	asn_DEF_IWLANUmtsHI2Operations_VisitedPLMNID_tags_1,
	sizeof(asn_DEF_IWLANUmtsHI2Operations_VisitedPLMNID_tags_1)
		/sizeof(asn_DEF_IWLANUmtsHI2Operations_VisitedPLMNID_tags_1[0]), /* 1 */
	asn_DEF_IWLANUmtsHI2Operations_VisitedPLMNID_tags_1,	/* Same as above */
	sizeof(asn_DEF_IWLANUmtsHI2Operations_VisitedPLMNID_tags_1)
		/sizeof(asn_DEF_IWLANUmtsHI2Operations_VisitedPLMNID_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		OCTET_STRING_constraint
	},
	0, 0,	/* No members */
	&asn_SPC_OCTET_STRING_specs	/* Additional specs */
};

