/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "UmtsHI2Operations"
 * 	found in "asn1-files/133108/UmtsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "UmtsHI2Operations_PacketDataHeaderReport.h"

#include "UmtsHI2Operations_PacketDataHeaderMapped.h"
#include "UmtsHI2Operations_PacketDataHeaderCopy.h"
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_UmtsHI2Operations_PacketDataHeaderReport_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_UmtsHI2Operations_PacketDataHeaderReport_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
asn_TYPE_member_t asn_MBR_UmtsHI2Operations_PacketDataHeaderReport_1[] = {
	{ ATF_POINTER, 0, offsetof(struct UmtsHI2Operations_PacketDataHeaderReport, choice.packetDataHeaderMapped),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UmtsHI2Operations_PacketDataHeaderMapped,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"packetDataHeaderMapped"
		},
	{ ATF_POINTER, 0, offsetof(struct UmtsHI2Operations_PacketDataHeaderReport, choice.packetDataHeaderCopy),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_UmtsHI2Operations_PacketDataHeaderCopy,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"packetDataHeaderCopy"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_UmtsHI2Operations_PacketDataHeaderReport_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* packetDataHeaderMapped */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 } /* packetDataHeaderCopy */
};
asn_CHOICE_specifics_t asn_SPC_UmtsHI2Operations_PacketDataHeaderReport_specs_1 = {
	sizeof(struct UmtsHI2Operations_PacketDataHeaderReport),
	offsetof(struct UmtsHI2Operations_PacketDataHeaderReport, _asn_ctx),
	offsetof(struct UmtsHI2Operations_PacketDataHeaderReport, present),
	sizeof(((struct UmtsHI2Operations_PacketDataHeaderReport *)0)->present),
	asn_MAP_UmtsHI2Operations_PacketDataHeaderReport_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
asn_TYPE_descriptor_t asn_DEF_UmtsHI2Operations_PacketDataHeaderReport = {
	"PacketDataHeaderReport",
	"PacketDataHeaderReport",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_UmtsHI2Operations_PacketDataHeaderReport_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_UmtsHI2Operations_PacketDataHeaderReport_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		CHOICE_constraint
	},
	asn_MBR_UmtsHI2Operations_PacketDataHeaderReport_1,
	2,	/* Elements count */
	&asn_SPC_UmtsHI2Operations_PacketDataHeaderReport_specs_1	/* Additional specs */
};

