/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "UmtsHI2Operations"
 * 	found in "asn1-files/133108/UmtsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "UmtsHI2Operations_PTCType.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_UmtsHI2Operations_PTCType_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_UmtsHI2Operations_PTCType_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  5,  5,  0,  26 }	/* (0..26,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_UmtsHI2Operations_PTCType_value2enum_1[] = {
	{ 1,	22,	"pTCStartofInterception" },
	{ 2,	15,	"pTCServinSystem" },
	{ 3,	20,	"pTCSessionInitiation" },
	{ 4,	26,	"pTCSessionAbandonEndRecord" },
	{ 5,	29,	"pTCSessionStartContinueRecord" },
	{ 6,	19,	"pTCSessionEndRecord" },
	{ 7,	38,	"pTCPre-EstablishedSessionSessionRecord" },
	{ 8,	23,	"pTCInstantPersonalAlert" },
	{ 9,	12,	"pTCPartyJoin" },
	{ 10,	12,	"pTCPartyDrop" },
	{ 11,	27,	"pTCPartyHold-RetrieveRecord" },
	{ 12,	20,	"pTCMediaModification" },
	{ 13,	21,	"pTCGroupAdvertizement" },
	{ 14,	16,	"pTCFloorConttrol" },
	{ 15,	18,	"pTCTargetPressence" },
	{ 16,	21,	"pTCAssociatePressence" },
	{ 17,	23,	"pTCListManagementEvents" },
	{ 18,	21,	"pTCAccessPolicyEvents" },
	{ 19,	24,	"pTCMediaTypeNotification" },
	{ 20,	19,	"pTCGroupCallRequest" },
	{ 21,	18,	"pTCGroupCallCancel" },
	{ 22,	20,	"pTCGroupCallResponse" },
	{ 23,	23,	"pTCGroupCallInterrogate" },
	{ 24,	25,	"pTCMCPTTImminentGroupCall" },
	{ 25,	5,	"pTCCC" },
	{ 26,	15,	"pTCRegistration" },
	{ 27,	13,	"pTCEncryption" }
	/* This list is extensible */
};
static int asn_validate_UmtsHI2Operations_PTCType_1(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_UmtsHI2Operations_PTCType value = *(e_UmtsHI2Operations_PTCType*)sptr;
    switch(value) {
    case UmtsHI2Operations_PTCType_pTCStartofInterception:
    case UmtsHI2Operations_PTCType_pTCServinSystem:
    case UmtsHI2Operations_PTCType_pTCSessionInitiation:
    case UmtsHI2Operations_PTCType_pTCSessionAbandonEndRecord:
    case UmtsHI2Operations_PTCType_pTCSessionStartContinueRecord:
    case UmtsHI2Operations_PTCType_pTCSessionEndRecord:
    case UmtsHI2Operations_PTCType_pTCPre_EstablishedSessionSessionRecord:
    case UmtsHI2Operations_PTCType_pTCInstantPersonalAlert:
    case UmtsHI2Operations_PTCType_pTCPartyJoin:
    case UmtsHI2Operations_PTCType_pTCPartyDrop:
    case UmtsHI2Operations_PTCType_pTCPartyHold_RetrieveRecord:
    case UmtsHI2Operations_PTCType_pTCMediaModification:
    case UmtsHI2Operations_PTCType_pTCGroupAdvertizement:
    case UmtsHI2Operations_PTCType_pTCFloorConttrol:
    case UmtsHI2Operations_PTCType_pTCTargetPressence:
    case UmtsHI2Operations_PTCType_pTCAssociatePressence:
    case UmtsHI2Operations_PTCType_pTCListManagementEvents:
    case UmtsHI2Operations_PTCType_pTCAccessPolicyEvents:
    case UmtsHI2Operations_PTCType_pTCMediaTypeNotification:
    case UmtsHI2Operations_PTCType_pTCGroupCallRequest:
    case UmtsHI2Operations_PTCType_pTCGroupCallCancel:
    case UmtsHI2Operations_PTCType_pTCGroupCallResponse:
    case UmtsHI2Operations_PTCType_pTCGroupCallInterrogate:
    case UmtsHI2Operations_PTCType_pTCMCPTTImminentGroupCall:
    case UmtsHI2Operations_PTCType_pTCCC:
    case UmtsHI2Operations_PTCType_pTCRegistration:
    case UmtsHI2Operations_PTCType_pTCEncryption:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_UmtsHI2Operations_PTCType_enum2value_1[] = {
	17,	/* pTCAccessPolicyEvents(18) */
	15,	/* pTCAssociatePressence(16) */
	24,	/* pTCCC(25) */
	26,	/* pTCEncryption(27) */
	13,	/* pTCFloorConttrol(14) */
	12,	/* pTCGroupAdvertizement(13) */
	20,	/* pTCGroupCallCancel(21) */
	22,	/* pTCGroupCallInterrogate(23) */
	19,	/* pTCGroupCallRequest(20) */
	21,	/* pTCGroupCallResponse(22) */
	7,	/* pTCInstantPersonalAlert(8) */
	16,	/* pTCListManagementEvents(17) */
	23,	/* pTCMCPTTImminentGroupCall(24) */
	11,	/* pTCMediaModification(12) */
	18,	/* pTCMediaTypeNotification(19) */
	9,	/* pTCPartyDrop(10) */
	10,	/* pTCPartyHold-RetrieveRecord(11) */
	8,	/* pTCPartyJoin(9) */
	6,	/* pTCPre-EstablishedSessionSessionRecord(7) */
	25,	/* pTCRegistration(26) */
	1,	/* pTCServinSystem(2) */
	3,	/* pTCSessionAbandonEndRecord(4) */
	5,	/* pTCSessionEndRecord(6) */
	2,	/* pTCSessionInitiation(3) */
	4,	/* pTCSessionStartContinueRecord(5) */
	0,	/* pTCStartofInterception(1) */
	14	/* pTCTargetPressence(15) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_UmtsHI2Operations_PTCType_specs_1 = {
	asn_MAP_UmtsHI2Operations_PTCType_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_UmtsHI2Operations_PTCType_enum2value_1,	/* N => "tag"; sorted by N */
	27,	/* Number of elements in the maps */
	28,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_UmtsHI2Operations_PTCType_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_UmtsHI2Operations_PTCType = {
	"PTCType",
	"PTCType",
	&asn_OP_NativeEnumerated,
	asn_DEF_UmtsHI2Operations_PTCType_tags_1,
	sizeof(asn_DEF_UmtsHI2Operations_PTCType_tags_1)
		/sizeof(asn_DEF_UmtsHI2Operations_PTCType_tags_1[0]), /* 1 */
	asn_DEF_UmtsHI2Operations_PTCType_tags_1,	/* Same as above */
	sizeof(asn_DEF_UmtsHI2Operations_PTCType_tags_1)
		/sizeof(asn_DEF_UmtsHI2Operations_PTCType_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_UmtsHI2Operations_PTCType_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_UmtsHI2Operations_PTCType_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_UmtsHI2Operations_PTCType_1
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_UmtsHI2Operations_PTCType_specs_1	/* Additional specs */
};

