/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "UmtsHI2Operations"
 * 	found in "asn1-files/133108/UmtsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "UmtsHI2Operations_Requesting-Node-Type.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_UmtsHI2Operations_Requesting_Node_Type_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_UmtsHI2Operations_Requesting_Node_Type_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  3,  3,  0,  4 }	/* (0..4,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_UmtsHI2Operations_Requesting_Node_Type_value2enum_1[] = {
	{ 1,	3,	"mSC" },
	{ 2,	10,	"sMS-Centre" },
	{ 3,	4,	"gMLC" },
	{ 4,	3,	"mME" },
	{ 5,	4,	"sGSN" }
	/* This list is extensible */
};
static int asn_validate_UmtsHI2Operations_Requesting_Node_Type_1(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_UmtsHI2Operations_Requesting_Node_Type value = *(e_UmtsHI2Operations_Requesting_Node_Type*)sptr;
    switch(value) {
    case UmtsHI2Operations_Requesting_Node_Type_mSC:
    case UmtsHI2Operations_Requesting_Node_Type_sMS_Centre:
    case UmtsHI2Operations_Requesting_Node_Type_gMLC:
    case UmtsHI2Operations_Requesting_Node_Type_mME:
    case UmtsHI2Operations_Requesting_Node_Type_sGSN:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_UmtsHI2Operations_Requesting_Node_Type_enum2value_1[] = {
	2,	/* gMLC(3) */
	3,	/* mME(4) */
	0,	/* mSC(1) */
	4,	/* sGSN(5) */
	1	/* sMS-Centre(2) */
	/* This list is extensible */
};
const asn_INTEGER_specifics_t asn_SPC_UmtsHI2Operations_Requesting_Node_Type_specs_1 = {
	asn_MAP_UmtsHI2Operations_Requesting_Node_Type_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_UmtsHI2Operations_Requesting_Node_Type_enum2value_1,	/* N => "tag"; sorted by N */
	5,	/* Number of elements in the maps */
	6,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_UmtsHI2Operations_Requesting_Node_Type_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_UmtsHI2Operations_Requesting_Node_Type = {
	"Requesting-Node-Type",
	"Requesting-Node-Type",
	&asn_OP_NativeEnumerated,
	asn_DEF_UmtsHI2Operations_Requesting_Node_Type_tags_1,
	sizeof(asn_DEF_UmtsHI2Operations_Requesting_Node_Type_tags_1)
		/sizeof(asn_DEF_UmtsHI2Operations_Requesting_Node_Type_tags_1[0]), /* 1 */
	asn_DEF_UmtsHI2Operations_Requesting_Node_Type_tags_1,	/* Same as above */
	sizeof(asn_DEF_UmtsHI2Operations_Requesting_Node_Type_tags_1)
		/sizeof(asn_DEF_UmtsHI2Operations_Requesting_Node_Type_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_UmtsHI2Operations_Requesting_Node_Type_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_UmtsHI2Operations_Requesting_Node_Type_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_UmtsHI2Operations_Requesting_Node_Type_1
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_UmtsHI2Operations_Requesting_Node_Type_specs_1	/* Additional specs */
};

