/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "UmtsHI2Operations"
 * 	found in "asn1-files/133108/UmtsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "UmtsHI2Operations_TPDU-direction.h"

/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#if !defined(ASN_DISABLE_OER_SUPPORT)
asn_oer_constraints_t asn_OER_type_UmtsHI2Operations_TPDU_direction_constr_1 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
asn_per_constraints_t asn_PER_type_UmtsHI2Operations_TPDU_direction_constr_1 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 2,  2,  0,  2 }	/* (0..2) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_UmtsHI2Operations_TPDU_direction_value2enum_1[] = {
	{ 1,	11,	"from-target" },
	{ 2,	9,	"to-target" },
	{ 3,	7,	"unknown" }
};
static int asn_validate_UmtsHI2Operations_TPDU_direction_1(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_UmtsHI2Operations_TPDU_direction value = *(e_UmtsHI2Operations_TPDU_direction*)sptr;
    switch(value) {
    case UmtsHI2Operations_TPDU_direction_from_target:
    case UmtsHI2Operations_TPDU_direction_to_target:
    case UmtsHI2Operations_TPDU_direction_unknown:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_UmtsHI2Operations_TPDU_direction_enum2value_1[] = {
	0,	/* from-target(1) */
	1,	/* to-target(2) */
	2	/* unknown(3) */
};
const asn_INTEGER_specifics_t asn_SPC_UmtsHI2Operations_TPDU_direction_specs_1 = {
	asn_MAP_UmtsHI2Operations_TPDU_direction_value2enum_1,	/* "tag" => N; sorted by tag */
	asn_MAP_UmtsHI2Operations_TPDU_direction_enum2value_1,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	0,	/* Enumeration is not extensible */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_UmtsHI2Operations_TPDU_direction_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
asn_TYPE_descriptor_t asn_DEF_UmtsHI2Operations_TPDU_direction = {
	"TPDU-direction",
	"TPDU-direction",
	&asn_OP_NativeEnumerated,
	asn_DEF_UmtsHI2Operations_TPDU_direction_tags_1,
	sizeof(asn_DEF_UmtsHI2Operations_TPDU_direction_tags_1)
		/sizeof(asn_DEF_UmtsHI2Operations_TPDU_direction_tags_1[0]), /* 1 */
	asn_DEF_UmtsHI2Operations_TPDU_direction_tags_1,	/* Same as above */
	sizeof(asn_DEF_UmtsHI2Operations_TPDU_direction_tags_1)
		/sizeof(asn_DEF_UmtsHI2Operations_TPDU_direction_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_UmtsHI2Operations_TPDU_direction_constr_1,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_UmtsHI2Operations_TPDU_direction_constr_1,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_UmtsHI2Operations_TPDU_direction_1
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_UmtsHI2Operations_TPDU_direction_specs_1	/* Additional specs */
};

