/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "UmtsHI2Operations"
 * 	found in "asn1-files/133108/UmtsHI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "UmtsHI2Operations_SMS-report.h"

#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_sms_initiator __attribute__((weak, alias("asn_DEF_sms_initiator_3")));
#else
static asn_TYPE_descriptor_t asn_DEF_sms_initiator_3;
static asn_TYPE_descriptor_t asn_DEF_sms_initiator;
__attribute__((constructor)) static void asn_DEF_sms_initiator_3_alias_init(void) {
	asn_DEF_sms_initiator = asn_DEF_sms_initiator_3;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_transfer_status __attribute__((weak, alias("asn_DEF_transfer_status_8")));
#else
static asn_TYPE_descriptor_t asn_DEF_transfer_status_8;
static asn_TYPE_descriptor_t asn_DEF_transfer_status;
__attribute__((constructor)) static void asn_DEF_transfer_status_8_alias_init(void) {
	asn_DEF_transfer_status = asn_DEF_transfer_status_8;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_other_message __attribute__((weak, alias("asn_DEF_other_message_13")));
#else
static asn_TYPE_descriptor_t asn_DEF_other_message_13;
static asn_TYPE_descriptor_t asn_DEF_other_message;
__attribute__((constructor)) static void asn_DEF_other_message_13_alias_init(void) {
	asn_DEF_other_message = asn_DEF_other_message_13;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_content_constraint_2(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1UL && size <= 270UL)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

#ifndef ASN1C_NO_UNSUFFIXED_PDU_ALIAS
#if defined(__ELF__) && (defined(__GNUC__) || defined(__clang__))
extern asn_TYPE_descriptor_t asn_DEF_sMS_Contents __attribute__((weak, alias("asn_DEF_sMS_Contents_2")));
#else
static asn_TYPE_descriptor_t asn_DEF_sMS_Contents_2;
static asn_TYPE_descriptor_t asn_DEF_sMS_Contents;
__attribute__((constructor)) static void asn_DEF_sMS_Contents_2_alias_init(void) {
	asn_DEF_sMS_Contents = asn_DEF_sMS_Contents_2;
}
#endif
#endif /* ASN1C_NO_UNSUFFIXED_PDU_ALIAS */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_sms_initiator_constr_3 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_sms_initiator_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_transfer_status_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_transfer_status_constr_8 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_type_other_message_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_type_other_message_constr_13 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_OER_SUPPORT)
static asn_oer_constraints_t asn_OER_memb_content_constr_18 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..270)) */};
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
static asn_per_constraints_t asn_PER_memb_content_constr_18 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 9,  9,  1,  270 }	/* (SIZE(1..270)) */,
	0, 0	/* No PER value map */
};
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
static const asn_INTEGER_enum_map_t asn_MAP_sms_initiator_value2enum_3[] = {
	{ 0,	6,	"target" },
	{ 1,	6,	"server" },
	{ 2,	15,	"undefined-party" }
	/* This list is extensible */
};
static int asn_validate_sms_initiator_3(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_UmtsHI2Operations_SMS_report__sMS_Contents__sms_initiator value = *(e_UmtsHI2Operations_SMS_report__sMS_Contents__sms_initiator*)sptr;
    switch(value) {
    case UmtsHI2Operations_SMS_report__sMS_Contents__sms_initiator_target:
    case UmtsHI2Operations_SMS_report__sMS_Contents__sms_initiator_server:
    case UmtsHI2Operations_SMS_report__sMS_Contents__sms_initiator_undefined_party:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_sms_initiator_enum2value_3[] = {
	1,	/* server(1) */
	0,	/* target(0) */
	2	/* undefined-party(2) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_sms_initiator_specs_3 = {
	asn_MAP_sms_initiator_value2enum_3,	/* "tag" => N; sorted by tag */
	asn_MAP_sms_initiator_enum2value_3,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	4,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_sms_initiator_tags_3[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sms_initiator_3 = {
	"sms-initiator",
	"sms-initiator",
	&asn_OP_NativeEnumerated,
	asn_DEF_sms_initiator_tags_3,
	sizeof(asn_DEF_sms_initiator_tags_3)
		/sizeof(asn_DEF_sms_initiator_tags_3[0]) - 1, /* 1 */
	asn_DEF_sms_initiator_tags_3,	/* Same as above */
	sizeof(asn_DEF_sms_initiator_tags_3)
		/sizeof(asn_DEF_sms_initiator_tags_3[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_sms_initiator_constr_3,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_sms_initiator_constr_3,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_sms_initiator_3
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_sms_initiator_specs_3	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_transfer_status_value2enum_8[] = {
	{ 0,	16,	"succeed-transfer" },
	{ 1,	20,	"not-succeed-transfer" },
	{ 2,	9,	"undefined" }
	/* This list is extensible */
};
static int asn_validate_transfer_status_8(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_UmtsHI2Operations_SMS_report__sMS_Contents__transfer_status value = *(e_UmtsHI2Operations_SMS_report__sMS_Contents__transfer_status*)sptr;
    switch(value) {
    case UmtsHI2Operations_SMS_report__sMS_Contents__transfer_status_succeed_transfer:
    case UmtsHI2Operations_SMS_report__sMS_Contents__transfer_status_not_succeed_transfer:
    case UmtsHI2Operations_SMS_report__sMS_Contents__transfer_status_undefined:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_transfer_status_enum2value_8[] = {
	1,	/* not-succeed-transfer(1) */
	0,	/* succeed-transfer(0) */
	2	/* undefined(2) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_transfer_status_specs_8 = {
	asn_MAP_transfer_status_value2enum_8,	/* "tag" => N; sorted by tag */
	asn_MAP_transfer_status_enum2value_8,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	4,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_transfer_status_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_transfer_status_8 = {
	"transfer-status",
	"transfer-status",
	&asn_OP_NativeEnumerated,
	asn_DEF_transfer_status_tags_8,
	sizeof(asn_DEF_transfer_status_tags_8)
		/sizeof(asn_DEF_transfer_status_tags_8[0]) - 1, /* 1 */
	asn_DEF_transfer_status_tags_8,	/* Same as above */
	sizeof(asn_DEF_transfer_status_tags_8)
		/sizeof(asn_DEF_transfer_status_tags_8[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_transfer_status_constr_8,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_transfer_status_constr_8,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_transfer_status_8
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_transfer_status_specs_8	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_other_message_value2enum_13[] = {
	{ 0,	3,	"yes" },
	{ 1,	2,	"no" },
	{ 2,	9,	"undefined" }
	/* This list is extensible */
};
static int asn_validate_other_message_13(const asn_TYPE_descriptor_t *td,
                       const void *sptr,
                       asn_app_constraint_failed_f *ctfailcb,
                       void* app_key) {
    if(! sptr) { return -1; }
    e_UmtsHI2Operations_SMS_report__sMS_Contents__other_message value = *(e_UmtsHI2Operations_SMS_report__sMS_Contents__other_message*)sptr;
    switch(value) {
    case UmtsHI2Operations_SMS_report__sMS_Contents__other_message_yes:
    case UmtsHI2Operations_SMS_report__sMS_Contents__other_message_no:
    case UmtsHI2Operations_SMS_report__sMS_Contents__other_message_undefined:
        return 0;
    }
    return -1;
}
static const unsigned int asn_MAP_other_message_enum2value_13[] = {
	1,	/* no(1) */
	2,	/* undefined(2) */
	0	/* yes(0) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_other_message_specs_13 = {
	asn_MAP_other_message_value2enum_13,	/* "tag" => N; sorted by tag */
	asn_MAP_other_message_enum2value_13,	/* N => "tag"; sorted by N */
	3,	/* Number of elements in the maps */
	4,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_other_message_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_other_message_13 = {
	"other-message",
	"other-message",
	&asn_OP_NativeEnumerated,
	asn_DEF_other_message_tags_13,
	sizeof(asn_DEF_other_message_tags_13)
		/sizeof(asn_DEF_other_message_tags_13[0]) - 1, /* 1 */
	asn_DEF_other_message_tags_13,	/* Same as above */
	sizeof(asn_DEF_other_message_tags_13)
		/sizeof(asn_DEF_other_message_tags_13[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		&asn_OER_type_other_message_constr_13,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		&asn_PER_type_other_message_constr_13,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		asn_validate_other_message_13
	},
	0, 0,	/* Defined elsewhere */
	&asn_SPC_other_message_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_UmtsHI2Operations_SMS_report__sMS_Contents_2[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UmtsHI2Operations_SMS_report__sMS_Contents, sms_initiator),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_sms_initiator_3,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sms-initiator"
		},
	{ ATF_POINTER, 4, offsetof(struct UmtsHI2Operations_SMS_report__sMS_Contents, transfer_status),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_transfer_status_8,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"transfer-status"
		},
	{ ATF_POINTER, 3, offsetof(struct UmtsHI2Operations_SMS_report__sMS_Contents, other_message),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_other_message_13,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"other-message"
		},
	{ ATF_POINTER, 2, offsetof(struct UmtsHI2Operations_SMS_report__sMS_Contents, content),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			&asn_OER_memb_content_constr_18,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			&asn_PER_memb_content_constr_18,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			memb_content_constraint_2
		},
		0, 0, /* No default value */
		"content"
		},
	{ ATF_POINTER, 1, offsetof(struct UmtsHI2Operations_SMS_report__sMS_Contents, sMSContentRemovedIndicator),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_BOOLEAN,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sMSContentRemovedIndicator"
		},
};
static const int asn_MAP_sMS_Contents_oms_2[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_sMS_Contents_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_sMS_Contents_tag2el_2[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* sms-initiator */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* transfer-status */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* other-message */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* content */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 } /* sMSContentRemovedIndicator */
};
static asn_SEQUENCE_specifics_t asn_SPC_sMS_Contents_specs_2 = {
	sizeof(struct UmtsHI2Operations_SMS_report__sMS_Contents),
	offsetof(struct UmtsHI2Operations_SMS_report__sMS_Contents, _asn_ctx),
	asn_MAP_sMS_Contents_tag2el_2,
	5,	/* Count of tags in the map */
	asn_MAP_sMS_Contents_oms_2,	/* Optional members */
	3, 1,	/* Root/Additions */
	4,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_sMS_Contents_2 = {
	"sMS-Contents",
	"sMS-Contents",
	&asn_OP_SEQUENCE,
	asn_DEF_sMS_Contents_tags_2,
	sizeof(asn_DEF_sMS_Contents_tags_2)
		/sizeof(asn_DEF_sMS_Contents_tags_2[0]) - 1, /* 1 */
	asn_DEF_sMS_Contents_tags_2,	/* Same as above */
	sizeof(asn_DEF_sMS_Contents_tags_2)
		/sizeof(asn_DEF_sMS_Contents_tags_2[0]), /* 2 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UmtsHI2Operations_SMS_report__sMS_Contents_2,
	5,	/* Elements count */
	&asn_SPC_sMS_Contents_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_UmtsHI2Operations_SMS_report_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct UmtsHI2Operations_SMS_report, sMS_Contents),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_sMS_Contents_2,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"sMS-Contents"
		},
};
static const ber_tlv_tag_t asn_DEF_UmtsHI2Operations_SMS_report_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UmtsHI2Operations_SMS_report_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 0, 0, 0 } /* sMS-Contents */
};
asn_SEQUENCE_specifics_t asn_SPC_UmtsHI2Operations_SMS_report_specs_1 = {
	sizeof(struct UmtsHI2Operations_SMS_report),
	offsetof(struct UmtsHI2Operations_SMS_report, _asn_ctx),
	asn_MAP_UmtsHI2Operations_SMS_report_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UmtsHI2Operations_SMS_report = {
	"SMS-report",
	"SMS-report",
	&asn_OP_SEQUENCE,
	asn_DEF_UmtsHI2Operations_SMS_report_tags_1,
	sizeof(asn_DEF_UmtsHI2Operations_SMS_report_tags_1)
		/sizeof(asn_DEF_UmtsHI2Operations_SMS_report_tags_1[0]), /* 1 */
	asn_DEF_UmtsHI2Operations_SMS_report_tags_1,	/* Same as above */
	sizeof(asn_DEF_UmtsHI2Operations_SMS_report_tags_1)
		/sizeof(asn_DEF_UmtsHI2Operations_SMS_report_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UmtsHI2Operations_SMS_report_1,
	1,	/* Elements count */
	&asn_SPC_UmtsHI2Operations_SMS_report_specs_1	/* Additional specs */
};

