/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "UmtsCS-HI2Operations"
 * 	found in "asn1-files/133108/UmtsCS-HI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "UmtsCS-HI2Operations_Current-Previous-Systems.h"

asn_TYPE_member_t asn_MBR_UmtsCS_HI2Operations_Current_Previous_Systems_1[] = {
	{ ATF_POINTER, 6, offsetof(struct UmtsCS_HI2Operations_Current_Previous_Systems, current_Serving_System_Identifier),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"current-Serving-System-Identifier"
		},
	{ ATF_POINTER, 5, offsetof(struct UmtsCS_HI2Operations_Current_Previous_Systems, current_Serving_MSC_Number),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"current-Serving-MSC-Number"
		},
	{ ATF_POINTER, 4, offsetof(struct UmtsCS_HI2Operations_Current_Previous_Systems, current_Serving_MSC_Address),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"current-Serving-MSC-Address"
		},
	{ ATF_POINTER, 3, offsetof(struct UmtsCS_HI2Operations_Current_Previous_Systems, previous_Serving_System_Identifier),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"previous-Serving-System-Identifier"
		},
	{ ATF_POINTER, 2, offsetof(struct UmtsCS_HI2Operations_Current_Previous_Systems, previous_Serving_MSC_Number),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"previous-Serving-MSC-Number"
		},
	{ ATF_POINTER, 1, offsetof(struct UmtsCS_HI2Operations_Current_Previous_Systems, previous_Serving_MSC_Address),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"previous-Serving-MSC-Address"
		},
};
static const int asn_MAP_UmtsCS_HI2Operations_Current_Previous_Systems_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_UmtsCS_HI2Operations_Current_Previous_Systems_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UmtsCS_HI2Operations_Current_Previous_Systems_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* current-Serving-System-Identifier */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* current-Serving-MSC-Number */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* current-Serving-MSC-Address */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* previous-Serving-System-Identifier */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* previous-Serving-MSC-Number */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 } /* previous-Serving-MSC-Address */
};
asn_SEQUENCE_specifics_t asn_SPC_UmtsCS_HI2Operations_Current_Previous_Systems_specs_1 = {
	sizeof(struct UmtsCS_HI2Operations_Current_Previous_Systems),
	offsetof(struct UmtsCS_HI2Operations_Current_Previous_Systems, _asn_ctx),
	asn_MAP_UmtsCS_HI2Operations_Current_Previous_Systems_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_UmtsCS_HI2Operations_Current_Previous_Systems_oms_1,	/* Optional members */
	6, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UmtsCS_HI2Operations_Current_Previous_Systems = {
	"Current-Previous-Systems",
	"Current-Previous-Systems",
	&asn_OP_SEQUENCE,
	asn_DEF_UmtsCS_HI2Operations_Current_Previous_Systems_tags_1,
	sizeof(asn_DEF_UmtsCS_HI2Operations_Current_Previous_Systems_tags_1)
		/sizeof(asn_DEF_UmtsCS_HI2Operations_Current_Previous_Systems_tags_1[0]), /* 1 */
	asn_DEF_UmtsCS_HI2Operations_Current_Previous_Systems_tags_1,	/* Same as above */
	sizeof(asn_DEF_UmtsCS_HI2Operations_Current_Previous_Systems_tags_1)
		/sizeof(asn_DEF_UmtsCS_HI2Operations_Current_Previous_Systems_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UmtsCS_HI2Operations_Current_Previous_Systems_1,
	6,	/* Elements count */
	&asn_SPC_UmtsCS_HI2Operations_Current_Previous_Systems_specs_1	/* Additional specs */
};

