/*
 * Generated by asn1c-5baed98c-2026-03-30 (https://github.com/Schramp/asn1c)
 * From ASN.1 module "UmtsCS-HI2Operations"
 * 	found in "asn1-files/133108/UmtsCS-HI2Operations.asn"
 * 	`asn1c -S ../../skeletons -pdu=PS-PDU -fcompound-names -fno-include-deps -fallow-newer-modules -fignore-missing-modules`
 */

#include "UmtsCS-HI2Operations_Change-Of-Target-Identity.h"

#include "HI2Operations_PartyInformation.h"
asn_TYPE_member_t asn_MBR_UmtsCS_HI2Operations_Change_Of_Target_Identity_1[] = {
	{ ATF_POINTER, 6, offsetof(struct UmtsCS_HI2Operations_Change_Of_Target_Identity, new_MSISDN),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HI2Operations_PartyInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"new-MSISDN"
		},
	{ ATF_POINTER, 5, offsetof(struct UmtsCS_HI2Operations_Change_Of_Target_Identity, old_MSISDN),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HI2Operations_PartyInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"old-MSISDN"
		},
	{ ATF_POINTER, 4, offsetof(struct UmtsCS_HI2Operations_Change_Of_Target_Identity, new_IMSI),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HI2Operations_PartyInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"new-IMSI"
		},
	{ ATF_POINTER, 3, offsetof(struct UmtsCS_HI2Operations_Change_Of_Target_Identity, old_IMSI),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HI2Operations_PartyInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"old-IMSI"
		},
	{ ATF_POINTER, 2, offsetof(struct UmtsCS_HI2Operations_Change_Of_Target_Identity, new_IMEI),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HI2Operations_PartyInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"new-IMEI"
		},
	{ ATF_POINTER, 1, offsetof(struct UmtsCS_HI2Operations_Change_Of_Target_Identity, old_IMEI),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_HI2Operations_PartyInformation,
		0,
		{
#if !defined(ASN_DISABLE_OER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
			0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
			0
		},
		0, 0, /* No default value */
		"old-IMEI"
		},
};
static const int asn_MAP_UmtsCS_HI2Operations_Change_Of_Target_Identity_oms_1[] = { 0, 1, 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_UmtsCS_HI2Operations_Change_Of_Target_Identity_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_UmtsCS_HI2Operations_Change_Of_Target_Identity_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 0, 0, 0 }, /* new-MSISDN */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, 0, 0 }, /* old-MSISDN */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 2, 0, 0 }, /* new-IMSI */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 3, 0, 0 }, /* old-IMSI */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 4, 0, 0 }, /* new-IMEI */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 5, 0, 0 } /* old-IMEI */
};
asn_SEQUENCE_specifics_t asn_SPC_UmtsCS_HI2Operations_Change_Of_Target_Identity_specs_1 = {
	sizeof(struct UmtsCS_HI2Operations_Change_Of_Target_Identity),
	offsetof(struct UmtsCS_HI2Operations_Change_Of_Target_Identity, _asn_ctx),
	asn_MAP_UmtsCS_HI2Operations_Change_Of_Target_Identity_tag2el_1,
	6,	/* Count of tags in the map */
	asn_MAP_UmtsCS_HI2Operations_Change_Of_Target_Identity_oms_1,	/* Optional members */
	4, 2,	/* Root/Additions */
	4,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_UmtsCS_HI2Operations_Change_Of_Target_Identity = {
	"Change-Of-Target-Identity",
	"Change-Of-Target-Identity",
	&asn_OP_SEQUENCE,
	asn_DEF_UmtsCS_HI2Operations_Change_Of_Target_Identity_tags_1,
	sizeof(asn_DEF_UmtsCS_HI2Operations_Change_Of_Target_Identity_tags_1)
		/sizeof(asn_DEF_UmtsCS_HI2Operations_Change_Of_Target_Identity_tags_1[0]), /* 1 */
	asn_DEF_UmtsCS_HI2Operations_Change_Of_Target_Identity_tags_1,	/* Same as above */
	sizeof(asn_DEF_UmtsCS_HI2Operations_Change_Of_Target_Identity_tags_1)
		/sizeof(asn_DEF_UmtsCS_HI2Operations_Change_Of_Target_Identity_tags_1[0]), /* 1 */
	{
#if !defined(ASN_DISABLE_OER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_OER_SUPPORT) */
#if !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_UPER_SUPPORT) || !defined(ASN_DISABLE_APER_SUPPORT) */
#if !defined(ASN_DISABLE_JER_SUPPORT)
		0,
#endif  /* !defined(ASN_DISABLE_JER_SUPPORT) */
		SEQUENCE_constraint
	},
	asn_MBR_UmtsCS_HI2Operations_Change_Of_Target_Identity_1,
	6,	/* Elements count */
	&asn_SPC_UmtsCS_HI2Operations_Change_Of_Target_Identity_specs_1	/* Additional specs */
};

